import React, { useEffect, useState } from 'react';
import { Alert, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { OperatingStructure } from '../../types/business';
const C = { bg: '#0B0F17', card: '#161F30', green: '#10B981', red: '#FF3D71', cyan: '#00D2FF', white: '#FFFFFF', muted: '#94A3B8', slate: '#263449', gold: '#E6B86A' };
type Props = { visible: boolean; cash: number; suggestedName?: string; onClose: () => void; onIncorporate: (name: string, structure: OperatingStructure, fee: number) => void };
export function BusinessRegistrationModal({ visible, cash, suggestedName = 'Apex Retail Corp', onClose, onIncorporate }: Props) {
  const [name, setName] = useState(suggestedName); const [structure, setStructure] = useState<OperatingStructure>('Licensed_Legal'); const [certified, setCertified] = useState(false);
  useEffect(() => { if (visible) { setName(suggestedName); setStructure('Licensed_Legal'); setCertified(false); } }, [visible, suggestedName]);
  const submit = () => { const fee = structure === 'Licensed_Legal' ? 2500 : 0; if (!name.trim()) return Alert.alert('Enterprise name required', 'Enter a registered enterprise name.'); if (cash < fee) return Alert.alert('Insufficient cash', 'Licensed incorporation requires $2,500.'); setCertified(true); setTimeout(() => onIncorporate(name.trim(), structure, fee), 450); };
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.shade}><View style={styles.modal}><Text style={styles.eyebrow}>CORPORATE REGISTRY</Text><Text style={styles.title}>Incorporate enterprise</Text><TextInput value={name} onChangeText={setName} placeholder="Enter Registered Enterprise Name" placeholderTextColor={C.muted} style={styles.input} /><Pressable onPress={() => setStructure('Licensed_Legal')} style={[styles.option, structure === 'Licensed_Legal' && styles.legalOn]}><Text style={styles.optionTitle}>LICENSED & REGISTERED</Text><Text style={styles.copy}>$2,500 incorporation · 15% sales tax · 0% police heat</Text><Text style={styles.safeBadge}>100% SAFE & AUDITED</Text></Pressable><Pressable onPress={() => setStructure('Shadow_Underground')} style={[styles.option, structure === 'Shadow_Underground' && styles.shadowOn]}><Text style={styles.optionTitle}>SHADOW / UNDERGROUND</Text><Text style={styles.copy}>$0 fee · 0% tax · +50% cash bonus · +2% heat/hour</Text></Pressable>{certified && <View style={styles.seal}><Text style={styles.sealText}>CERTIFIED & ACTIVE</Text></View>}<View style={styles.actions}><Pressable onPress={onClose} style={styles.cancel}><Text style={styles.cancelText}>CANCEL</Text></Pressable><Pressable onPress={submit} style={styles.sign}><Text style={styles.signText}>SIGN & INCORPORATE</Text></Pressable></View></View></View></Modal>;
}
const styles = StyleSheet.create({ shade: { flex: 1, backgroundColor: 'rgba(0,0,0,.82)', justifyContent: 'flex-end' }, modal: { backgroundColor: C.card, padding: 20, paddingBottom: 34, borderTopLeftRadius: 24, borderTopRightRadius: 24, borderWidth: 1, borderColor: C.green }, eyebrow: { color: C.cyan, fontSize: 11, fontWeight: '900', letterSpacing: 1.5 }, title: { color: C.white, fontSize: 26, fontWeight: '900', marginTop: 6, marginBottom: 16 }, input: { color: C.white, backgroundColor: C.bg, borderWidth: 1, borderColor: C.slate, borderRadius: 12, padding: 14, marginBottom: 12 }, option: { borderWidth: 1, borderColor: C.slate, borderRadius: 14, padding: 14, marginTop: 9 }, legalOn: { borderColor: C.green, backgroundColor: '#12372E' }, shadowOn: { borderColor: C.red, backgroundColor: '#381825' }, optionTitle: { color: C.white, fontWeight: '900' }, copy: { color: C.muted, fontSize: 12, lineHeight: 18, marginTop: 5 }, safeBadge: { color: C.green, fontSize: 10, fontWeight: '900', marginTop: 8 }, seal: { borderWidth: 2, borderColor: C.green, padding: 11, alignItems: 'center', marginTop: 16 }, sealText: { color: C.green, fontWeight: '900', letterSpacing: 2 }, actions: { flexDirection: 'row', gap: 10, marginTop: 18 }, cancel: { flex: 1, alignItems: 'center', padding: 14 }, cancelText: { color: C.muted, fontWeight: '900' }, sign: { flex: 2, alignItems: 'center', backgroundColor: C.green, padding: 14, borderRadius: 10 }, signText: { color: C.bg, fontWeight: '900', fontSize: 12 } });
export default BusinessRegistrationModal;
