import React, { useEffect, useRef, useState } from 'react';
import { Alert, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { OperatingStructure } from '../../types/business';
import { formatCurrency } from '../../utils/formatCurrency';

const C = { bg: '#08111F', card: '#122238', green: '#28E39A', red: '#FF647F', cyan: '#49C8FF', white: '#F8FAFC', muted: '#8EA4BA', slate: '#29425D', gold: '#FFC857' };
type Props = { visible: boolean; cash: number; suggestedName?: string; onClose: () => void; onIncorporate: (name: string, structure: OperatingStructure, fee: number) => void };

export function BusinessRegistrationModal({ visible, cash, suggestedName = 'Copper & Bloom Market', onClose, onIncorporate }: Props) {
  const [name, setName] = useState(suggestedName); const [structure, setStructure] = useState<OperatingStructure>('Licensed_Legal'); const [certified, setCertified] = useState(false); const incorporationTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  useEffect(() => { if (visible) { setName(suggestedName); setStructure('Licensed_Legal'); setCertified(false); } return () => { if (incorporationTimer.current) clearTimeout(incorporationTimer.current); }; }, [visible, suggestedName]);
  const submit = () => { const fee = structure === 'Licensed_Legal' ? 2500 : 0; if (!name.trim()) return Alert.alert('Name your company', 'Choose a registered company name to continue.'); if (cash < fee) return Alert.alert('Insufficient cash', `This charter requires ${formatCurrency(fee)} in filing fees.`); if (incorporationTimer.current) clearTimeout(incorporationTimer.current); setCertified(true); incorporationTimer.current = setTimeout(() => { incorporationTimer.current = null; onIncorporate(name.trim(), structure, fee); }, 450); };
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.shade}><View style={styles.modal}><View style={styles.grabber} /><View style={styles.top}><View><Text style={styles.eyebrow}>NEW VENTURE · UNITED STATES</Text><Text style={styles.title}>Choose your company charter</Text></View><Pressable onPress={onClose} style={styles.close}><Text style={styles.closeText}>×</Text></Pressable></View><Text style={styles.sub}>Your first charter sets the risk, tax profile, and upside of this business.</Text><TextInput value={name} onChangeText={setName} returnKeyType="done" placeholder="Company name" placeholderTextColor={C.muted} style={styles.input} /><Pressable onPress={() => setStructure('Licensed_Legal')} style={[styles.option, structure === 'Licensed_Legal' && styles.legalOn]}><View style={styles.optionTop}><View style={[styles.optionIcon, { backgroundColor: '#28E39A22' }]}><Text style={styles.iconText}>✓</Text></View><View style={{ flex: 1 }}><Text style={styles.optionTitle}>MAIN STREET LEGAL</Text><Text style={styles.copy}>$2,500 filing fee · 15% audited tax</Text></View>{structure === 'Licensed_Legal' && <Text style={styles.selected}>SELECTED</Text>}</View><Text style={styles.benefit}>Bankable, stable, and eligible for government contracts.</Text></Pressable><Pressable onPress={() => setStructure('Shadow_Underground')} style={[styles.option, structure === 'Shadow_Underground' && styles.shadowOn]}><View style={styles.optionTop}><View style={[styles.optionIcon, { backgroundColor: '#FF647F22' }]}><Text style={[styles.iconText, { color: C.red }]}>!</Text></View><View style={{ flex: 1 }}><Text style={[styles.optionTitle, { color: C.red }]}>SHADOW ROUTE</Text><Text style={styles.copy}>$0 filing fee · higher margin · rising heat</Text></View>{structure === 'Shadow_Underground' && <Text style={[styles.selected, { color: C.red }]}>SELECTED</Text>}</View><Text style={styles.benefit}>Move faster with more upside, but police heat can trigger setbacks.</Text></Pressable><View style={styles.cashRow}><Text style={styles.cashLabel}>LIQUID CASH AVAILABLE</Text><Text style={styles.cashValue}>{formatCurrency(cash)}</Text></View>{certified && <View style={styles.seal}><Text style={styles.sealText}>CHARTER VERIFIED · READY TO TRADE</Text></View>}<View style={styles.actions}><Pressable onPress={onClose} style={styles.cancel}><Text style={styles.cancelText}>NOT YET</Text></Pressable><Pressable onPress={submit} style={styles.sign}><Text style={styles.signText}>LAUNCH COMPANY ›</Text></Pressable></View></View></View></Modal>;
}
const styles = StyleSheet.create({ shade: { flex: 1, backgroundColor: 'rgba(1,7,15,.84)', justifyContent: 'flex-end' }, modal: { backgroundColor: C.card, padding: 18, paddingBottom: 30, borderTopLeftRadius: 26, borderTopRightRadius: 26, borderWidth: 1, borderColor: '#2C637F' }, grabber: { alignSelf: 'center', width: 42, height: 4, borderRadius: 4, backgroundColor: C.slate, marginBottom: 17 }, top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, eyebrow: { color: C.cyan, fontSize: 8, fontWeight: '900', letterSpacing: 1.1 }, title: { color: C.white, fontSize: 23, lineHeight: 28, fontWeight: '900', marginTop: 5, maxWidth: 290 }, close: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#1C334B', alignItems: 'center', justifyContent: 'center' }, closeText: { color: C.white, fontSize: 24, lineHeight: 26 }, sub: { color: C.muted, fontSize: 11, lineHeight: 16, marginTop: 8, marginBottom: 13 }, input: { color: C.white, backgroundColor: C.bg, borderWidth: 1, borderColor: C.slate, borderRadius: 12, padding: 13, marginBottom: 3, fontSize: 14 }, option: { borderWidth: 1, borderColor: C.slate, borderRadius: 15, padding: 13, marginTop: 10 }, legalOn: { borderColor: C.green, backgroundColor: '#11372F' }, shadowOn: { borderColor: C.red, backgroundColor: '#3B1C2A' }, optionTop: { flexDirection: 'row', alignItems: 'center' }, optionIcon: { width: 30, height: 30, borderRadius: 15, alignItems: 'center', justifyContent: 'center', marginRight: 9 }, iconText: { color: C.green, fontSize: 17, fontWeight: '900' }, optionTitle: { color: C.white, fontSize: 11, fontWeight: '900', letterSpacing: .8 }, copy: { color: C.muted, fontSize: 10, marginTop: 3 }, selected: { color: C.green, fontSize: 7, fontWeight: '900', letterSpacing: .6 }, benefit: { color: '#B1C6D8', fontSize: 10, lineHeight: 15, marginTop: 9, paddingLeft: 39 }, cashRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 16, paddingTop: 12, borderTopWidth: 1, borderTopColor: C.slate }, cashLabel: { color: C.muted, fontSize: 8, fontWeight: '900', letterSpacing: .7 }, cashValue: { color: C.white, fontSize: 14, fontWeight: '900' }, seal: { borderWidth: 1, borderColor: C.green, backgroundColor: '#11372F', padding: 10, alignItems: 'center', marginTop: 14, borderRadius: 9 }, sealText: { color: C.green, fontSize: 9, fontWeight: '900', letterSpacing: 1 }, actions: { flexDirection: 'row', gap: 9, marginTop: 17 }, cancel: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 14 }, cancelText: { color: C.muted, fontWeight: '900', fontSize: 10 }, sign: { flex: 2, alignItems: 'center', backgroundColor: C.green, padding: 14, borderRadius: 11 }, signText: { color: C.bg, fontWeight: '900', fontSize: 11, letterSpacing: .3 } });
export default BusinessRegistrationModal;
