import React, { useEffect, useState } from 'react';
import { Alert, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { businessValuation, createIPOListing, getIPOEligibility, normalizeTicker } from '../../engine/ipoEngine';
import { BusinessEntity } from '../../types/business';
import { IPOListing } from '../../types/ipo';
import { formatCurrency } from '../../utils/formatCurrency';

const C = { bg: '#08111F', card: '#122238', green: '#28E39A', red: '#FF647F', cyan: '#49C8FF', white: '#F8FAFC', muted: '#8EA4BA', slate: '#29425D', gold: '#FFC857' };
type Props = { visible: boolean; business: BusinessEntity | null; listing?: IPOListing | null; cash: number; gameTimestamp: number; onClose: () => void; onLaunch: (listing: IPOListing) => void };

export function IPOLaunchModal({ visible, business, listing, cash, gameTimestamp, onClose, onLaunch }: Props) {
  const [ticker, setTicker] = useState('');
  useEffect(() => { if (visible && business) setTicker(normalizeTicker(business.name)); }, [visible, business]);
  if (!business) return null;
  const eligibility = getIPOEligibility(business, listing);
  const preview = createIPOListing(business, gameTimestamp, ticker || undefined);
  const launch = () => { if (!eligibility.eligible) return Alert.alert('IPO WINDOW CLOSED', eligibility.reason); onLaunch({ ...preview, ticker: normalizeTicker(ticker) }); };
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.shade}><SafeAreaView edges={['bottom', 'left', 'right']} style={styles.sheet}><View style={styles.grabber} /><View style={styles.header}><View><Text style={styles.eyebrow}>NASDAQ PRIVATE MARKET · LATE GAME</Text><Text style={styles.title}>Take {business.name} public</Text></View><Pressable onPress={onClose} style={styles.close}><Text style={styles.closeText}>×</Text></Pressable></View><Text style={styles.copy}>{eligibility.reason}</Text><View style={styles.valuation}><Text style={styles.label}>ESTIMATED PRIVATE VALUATION</Text><Text style={styles.value}>{formatCurrency(eligibility.valuation)}</Text><Text style={styles.caption}>Based on annualized net profit, sector multiple, and operating assets.</Text></View><View style={styles.stats}><Stat label="PUBLIC FLOAT" value={`${preview.publicShares.toLocaleString()} shares`} /><Stat label="OWNERS RETAINED" value="80% founder stake" /><Stat label="IPO PRICE" value={formatCurrency(preview.ipoPrice)} /></View><Text style={styles.fieldLabel}>PUBLIC TICKER</Text><View style={styles.tickerRow}><TextInput value={ticker} onChangeText={value => setTicker(value.replace(/[^a-zA-Z]/g, '').toUpperCase().slice(0, 3))} maxLength={3} autoCapitalize="characters" placeholder="ABC" placeholderTextColor={C.muted} style={styles.input} /><Text style={styles.tickerHint}>{preview.companyName} · Class A</Text></View><View style={styles.raise}><View><Text style={styles.raiseLabel}>GROWTH CAPITAL RAISED</Text><Text style={styles.raiseValue}>{formatCurrency(preview.capitalRaised)}</Text></View><Text style={styles.raiseCopy}>Deposited instantly<br />to liquid cash</Text></View>{eligibility.eligible ? <Pressable onPress={launch} style={styles.launch}><Text style={styles.launchText}>RING THE OPENING BELL ›</Text></Pressable> : <View style={styles.locked}><Text style={styles.lockedText}>IPO LOCKED · BUILD MORE VALUE</Text></View>}<Text style={styles.disclaimer}>Public offerings sell a 20% minority stake. Market price will move with your company's performance.</Text></SafeAreaView></View></Modal>;
}
function Stat({ label, value }: { label: string; value: string }) { return <View style={styles.stat}><Text style={styles.statLabel}>{label}</Text><Text style={styles.statValue}>{value}</Text></View>; }
const styles = StyleSheet.create({ shade: { flex: 1, backgroundColor: 'rgba(1,7,15,.86)', justifyContent: 'flex-end' }, sheet: { backgroundColor: C.card, borderTopLeftRadius: 26, borderTopRightRadius: 26, borderTopWidth: 1, borderColor: C.cyan, padding: 18 }, grabber: { alignSelf: 'center', width: 42, height: 4, borderRadius: 4, backgroundColor: C.slate, marginBottom: 17 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, eyebrow: { color: C.cyan, fontSize: 8, fontWeight: '900', letterSpacing: 1 }, title: { color: C.white, fontSize: 22, lineHeight: 27, fontWeight: '900', marginTop: 5, maxWidth: 300 }, close: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#1C334B', alignItems: 'center', justifyContent: 'center' }, closeText: { color: C.white, fontSize: 24 }, copy: { color: C.muted, fontSize: 11, lineHeight: 16, marginTop: 9 }, valuation: { backgroundColor: C.bg, borderRadius: 15, padding: 15, borderWidth: 1, borderColor: C.slate, marginTop: 15 }, label: { color: C.muted, fontSize: 8, fontWeight: '900', letterSpacing: 1 }, value: { color: C.green, fontSize: 27, fontWeight: '900', marginTop: 5 }, caption: { color: C.muted, fontSize: 9, marginTop: 5 }, stats: { flexDirection: 'row', gap: 8, marginTop: 10 }, stat: { flex: 1, backgroundColor: '#1A3048', borderRadius: 10, padding: 10 }, statLabel: { color: C.muted, fontSize: 7, fontWeight: '900' }, statValue: { color: C.white, fontSize: 11, fontWeight: '900', marginTop: 5 }, fieldLabel: { color: C.muted, fontSize: 8, fontWeight: '900', letterSpacing: 1, marginTop: 15 }, tickerRow: { flexDirection: 'row', alignItems: 'center', gap: 10 }, input: { width: 76, color: C.white, backgroundColor: C.bg, borderWidth: 1, borderColor: C.cyan, borderRadius: 10, padding: 11, fontSize: 18, fontWeight: '900', textAlign: 'center', letterSpacing: 2, marginTop: 6 }, tickerHint: { color: C.muted, fontSize: 10, flex: 1 }, raise: { backgroundColor: '#12372F', borderRadius: 14, padding: 14, marginTop: 15, borderWidth: 1, borderColor: C.green, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, raiseLabel: { color: C.green, fontSize: 8, fontWeight: '900', letterSpacing: .8 }, raiseValue: { color: C.white, fontSize: 22, fontWeight: '900', marginTop: 4 }, raiseCopy: { color: '#9ED9C4', fontSize: 10, lineHeight: 15, textAlign: 'right' }, launch: { backgroundColor: C.green, borderRadius: 12, padding: 15, alignItems: 'center', marginTop: 14 }, launchText: { color: C.bg, fontSize: 12, fontWeight: '900', letterSpacing: .6 }, locked: { backgroundColor: '#263449', borderRadius: 12, padding: 15, alignItems: 'center', marginTop: 14 }, lockedText: { color: C.muted, fontSize: 11, fontWeight: '900' }, disclaimer: { color: C.muted, fontSize: 8, lineHeight: 12, textAlign: 'center', marginTop: 11 } });
export default IPOLaunchModal;
