import React from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { BusinessEntity } from '../types/game';
import { formatCurrency } from '../utils/formatCurrency';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { BusinessStackParamList } from './businessNavigation';
const C = { bg: '#0B0F17', panel: '#121923', green: '#00E676', red: '#FF3D71', cyan: '#00D2FF', text: '#F7FAFC', muted: '#8190A5', slate: '#1E293B' };
export function BusinessWorkforceScreen({ route }: NativeStackScreenProps<BusinessStackParamList, 'BusinessWorkforce'>) {
  const { business, cash, onCashChange, onChange } = route.params;
  const retail = business.resources.kind === 'retail' ? business.resources : null;
  const hireCashier = () => { const cost = 1800; if (cash < cost) return Alert.alert('Insufficient cash', `Hiring a cashier requires ${formatCurrency(cost)}.`); onCashChange(value => value - cost); onChange({ ...business, workforce: { ...business.workforce, headcount: business.workforce.headcount + 1, morale: Math.min(100, business.workforce.morale + 2) }, operationalLog: [`[Staff] Cashier hired · +300 customers/hr capacity.`, ...business.operationalLog].slice(0, 5) }); };
  const hireManager = () => { const cost = 12000; if (business.workforce.automationManagerHired) return; if (cash < cost) return Alert.alert('Insufficient cash', `General Manager hiring requires ${formatCurrency(cost)}.`); onCashChange(value => value - cost); onChange({ ...business, workforce: { ...business.workforce, automationManagerHired: true, morale: Math.min(100, business.workforce.morale + 5) }, operationalLog: [`[Staff] General Manager hired · smart auto-restocking unlocked.`, ...business.operationalLog].slice(0, 5) }); };
  const bonus = () => { const cost = 500; if (cash < cost) return Alert.alert('Insufficient cash', 'Morale bonus requires $500.'); onCashChange(value => value - cost); onChange({ ...business, workforce: { ...business.workforce, morale: Math.min(100, business.workforce.morale + 15) }, operationalLog: [`[Payroll] - $500.00 staff bonus disbursed.`, ...business.operationalLog].slice(0, 5), transactionLedger: [{ id: `payroll-${Date.now()}`, at: Date.now(), type: 'payroll' as const, amount: -500, label: '[Payroll] Staff morale bonus disbursed' }, ...(business.transactionLedger || [])].slice(0, 20) }); };
  return <SafeAreaView edges={['top', 'left', 'right']} style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>PEOPLE / WORKFORCE</Text><Text style={styles.title}>Staff department</Text><Text style={styles.subtitle}>Build a team that protects throughput, morale, and operating continuity.</Text><View style={styles.card}><Metric label="Headcount" value={`${business.workforce.headcount} employees`} /><Metric label="Morale" value={`${business.workforce.morale.toFixed(0)}%`} /><Metric label="Automation manager" value={business.workforce.automationManagerHired ? 'HIRED · AUTO-RESTOCK ENABLED' : 'NOT HIRED'} /></View><View style={styles.card}><Text style={styles.cardTitle}>ROSTER ACTIONS</Text><Action title="HIRE CASHIER / CLERK" copy="$1,800 onboarding · +300 customers/hr handling capacity" onPress={hireCashier} /><Action title={business.workforce.automationManagerHired ? 'GENERAL MANAGER ACTIVE' : 'HIRE STORE GENERAL MANAGER'} copy={business.workforce.automationManagerHired ? 'Smart inventory decisions are enabled.' : '$12,000 appointment · unlocks smart auto-restocking'} onPress={hireManager} disabled={business.workforce.automationManagerHired} /><Action title="INVENTORY CLERK" copy="$4,500 appointment · reduces stock waste by 10%" onPress={() => { if (cash < 4500) return Alert.alert('Insufficient cash', 'Inventory Clerk appointment requires $4,500.'); onCashChange(value => value - 4500); onChange({ ...business, operationalLog: ['[Staff] Inventory Clerk appointed · stock waste reduced by 10%.', ...business.operationalLog].slice(0, 5) }); }} /></View><View style={styles.card}><Text style={styles.cardTitle}>MORALE CENTER</Text><Text style={styles.muted}>A stable workforce keeps the business productive. Bonuses are recorded in the audit ledger.</Text><Action title="DISTRIBUTE STAFF BONUS" copy="$500 · +15 morale" onPress={bonus} /></View></ScrollView></SafeAreaView>;
}
function Metric({ label, value }: { label: string; value: string }) { return <View style={styles.metric}><Text style={styles.muted}>{label}</Text><Text style={styles.metricValue}>{value}</Text></View>; }
function Action({ title, copy, onPress, disabled = false }: { title: string; copy: string; onPress: () => void; disabled?: boolean }) { return <Pressable disabled={disabled} onPress={onPress} style={[styles.action, disabled && styles.disabled]}><Text style={styles.actionTitle}>{title}</Text><Text style={styles.muted}>{copy}</Text></Pressable>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: C.bg }, content: { padding: 20, paddingBottom: 120 }, eyebrow: { color: C.cyan, fontSize: 11, fontWeight: '800', letterSpacing: 1.5 }, title: { color: C.text, fontSize: 30, fontWeight: '900', marginTop: 8 }, subtitle: { color: C.muted, lineHeight: 21, marginTop: 8, marginBottom: 20 }, card: { backgroundColor: C.panel, borderRadius: 20, padding: 18, marginBottom: 16, borderWidth: 1, borderColor: C.slate }, cardTitle: { color: C.text, fontWeight: '900', letterSpacing: 1, marginBottom: 12 }, metric: { paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: C.slate }, metricValue: { color: C.text, fontSize: 18, fontWeight: '800', marginTop: 4 }, action: { padding: 15, backgroundColor: '#182231', borderRadius: 14, marginTop: 10 }, actionTitle: { color: C.green, fontWeight: '900', marginBottom: 5 }, muted: { color: C.muted, fontSize: 12, lineHeight: 18 }, disabled: { opacity: .5 } });
export default BusinessWorkforceScreen;
