import * as Haptics from 'expo-haptics';
import React from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { formatCurrency } from '../utils/formatCurrency';
import { RETAIL_BATCH_COST, RETAIL_BATCH_UNITS, RETAIL_PAYROLL_MONTHLY, RETAIL_RENT_UTILITIES_MONTHLY, RETAIL_SELLING_PRICE, RETAIL_SETUP_COST, RetailShopState, retailHourlyAccounting } from '../types/retail';
export function BusinessScreen({ state, cash, onStateChange, onCashChange }: { state: RetailShopState; cash: number; onStateChange: (next: RetailShopState) => void; onCashChange: (next: (value: number) => number) => void }) {
  const accounting = retailHourlyAccounting(state);
  const buyShop = () => { if (state.owned) return; if (cash < RETAIL_SETUP_COST) return Alert.alert('Insufficient cash', `Retail Shop setup requires ${formatCurrency(RETAIL_SETUP_COST)}.`); Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success); onCashChange(v => v - RETAIL_SETUP_COST); onStateChange({ ...state, owned: true }); };
  const restock = () => { if (!state.owned) return Alert.alert('Purchase the shop first', 'The retail inventory system unlocks after setup.'); if (cash < RETAIL_BATCH_COST) return Alert.alert('Insufficient cash', `Each batch costs ${formatCurrency(RETAIL_BATCH_COST)}.`); Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium); onCashChange(v => v - RETAIL_BATCH_COST); onStateChange({ ...state, inventoryUnits: state.inventoryUnits + RETAIL_BATCH_UNITS }); };
  const hire = () => { if (state.staffHired) return; if (cash < RETAIL_PAYROLL_MONTHLY) return Alert.alert('Insufficient cash', `Hiring requires the first monthly payroll reserve of ${formatCurrency(RETAIL_PAYROLL_MONTHLY)}.`); Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success); onCashChange(v => v - RETAIL_PAYROLL_MONTHLY); onStateChange({ ...state, staffHired: true }); };
  return <SafeAreaView edges={['top', 'left', 'right']} style={styles.safe}><Text style={styles.eyebrow}>BUSINESS / RETAIL</Text><Text style={styles.title}>Retail Shop</Text><Text style={styles.subtitle}>A real inventory-ledger business. No inventory means no revenue.</Text>{!state.owned ? <View style={styles.hero}><Text style={styles.heroTitle}>LOCAL RETAIL SHOP</Text><Text style={styles.muted}>Setup includes storefront registration and point-of-sale equipment.</Text><Text style={styles.big}>{formatCurrency(RETAIL_SETUP_COST)}</Text><Pressable onPress={buyShop} style={styles.primary}><Text style={styles.primaryText}>PURCHASE SHOP</Text></Pressable></View> : <><View style={styles.profitCard}><Text style={styles.muted}>NET HOURLY PROFIT</Text><Text style={[styles.profit, accounting.netProfit >= 0 ? styles.green : styles.red]}>{formatCurrency(accounting.netProfit)}</Text><Text style={styles.muted}>Revenue {formatCurrency(accounting.revenue)} · COGS {formatCurrency(accounting.cogs)} · Rent {formatCurrency(accounting.rent)} · Payroll {formatCurrency(accounting.payroll)}</Text></View><View style={styles.grid}><Metric label="INVENTORY" value={`${state.inventoryUnits} units`} /><Metric label="SELLING PRICE" value={`${formatCurrency(RETAIL_SELLING_PRICE)} / unit`} /><Metric label="RENT & UTILITIES" value={`${formatCurrency(RETAIL_RENT_UTILITIES_MONTHLY)} / month`} /><Metric label="CASHIER PAYROLL" value={state.staffHired ? `${formatCurrency(RETAIL_PAYROLL_MONTHLY)} / month` : 'Not hired'} /></View><View style={styles.section}><Text style={styles.sectionTitle}>INVENTORY SYSTEM</Text><Text style={styles.muted}>{formatCurrency(RETAIL_BATCH_COST)} buys {RETAIL_BATCH_UNITS} units. Staff sell up to 10 units/hour.</Text><Pressable onPress={restock} style={styles.primary}><Text style={styles.primaryText}>BUY STOCK BATCH · {formatCurrency(RETAIL_BATCH_COST)}</Text></Pressable></View><View style={styles.section}><Text style={styles.sectionTitle}>CASHIER STAFF</Text><Text style={styles.muted}>{state.staffHired ? 'Automated sales active. Payroll is deducted in the hourly accounting.' : `Hire staff for ${formatCurrency(RETAIL_PAYROLL_MONTHLY)} monthly payroll.`}</Text>{!state.staffHired && <Pressable onPress={hire} style={styles.secondary}><Text style={styles.secondaryText}>HIRE CASHIER</Text></Pressable>}</View></>}</SafeAreaView>;
}
function Metric({ label, value }: { label: string; value: string }) { return <View style={styles.metric}><Text style={styles.muted}>{label}</Text><Text style={styles.metricValue}>{value}</Text></View>; }
const styles = StyleSheet.create({ safe: { flex: 1 }, eyebrow: { color: '#00D2FF', fontSize: 10, fontWeight: '900', letterSpacing: 2 }, title: { color: '#F7FAFC', fontSize: 30, fontWeight: '900', marginVertical: 8 }, subtitle: { color: '#8190A5', lineHeight: 19 }, hero: { backgroundColor: '#121923', borderRadius: 18, padding: 20, marginTop: 18 }, heroTitle: { color: '#E6B86A', fontSize: 16, fontWeight: '900' }, big: { color: '#F7FAFC', fontSize: 32, fontWeight: '900', marginVertical: 20 }, primary: { backgroundColor: '#00E676', borderRadius: 11, padding: 14, alignItems: 'center', marginTop: 12 }, primaryText: { color: '#0B0F17', fontWeight: '900', fontSize: 12 }, secondary: { borderColor: '#00D2FF', borderWidth: 1, borderRadius: 11, padding: 14, alignItems: 'center', marginTop: 14 }, secondaryText: { color: '#00D2FF', fontWeight: '900', fontSize: 12 }, profitCard: { backgroundColor: '#121923', borderRadius: 18, padding: 18, marginTop: 18 }, profit: { fontSize: 34, fontWeight: '900', marginVertical: 5 }, green: { color: '#00E676' }, red: { color: '#FF3D71' }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 12 }, metric: { width: '48%', backgroundColor: '#182231', borderRadius: 12, padding: 13 }, metricValue: { color: '#F7FAFC', fontWeight: '900', marginTop: 7 }, section: { backgroundColor: '#121923', borderRadius: 16, padding: 16, marginTop: 12 }, sectionTitle: { color: '#F7FAFC', fontWeight: '900', letterSpacing: 1, marginBottom: 8 }, muted: { color: '#8190A5', fontSize: 12, lineHeight: 18 } });
