import React from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { BusinessEntity } from '../types/game';
import { formatCurrency } from '../utils/formatCurrency';
import { getWarehouseCapacity } from '../engine/businessEngine';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { BusinessStackParamList } from './businessNavigation';
const C = { bg: '#0B0F17', panel: '#121923', green: '#00E676', red: '#FF3D71', cyan: '#00D2FF', text: '#F7FAFC', muted: '#8190A5', slate: '#1E293B', gold: '#E6B86A' };
export function BusinessExpansionScreen({ route }: NativeStackScreenProps<BusinessStackParamList, 'BusinessExpansion'>) {
  const { business, cash, onCashChange, onChange } = route.params;
  const retail = business.resources.kind === 'retail' ? business.resources : null;
  const upgrade = () => { if (!retail) return Alert.alert('Expansion unavailable', 'This dedicated expansion control is currently configured for retail operations.'); const next = retail.floorStage === 'Corner Kiosk' ? { stage: 'Convenience Store' as const, capacity: 10000, cost: 15000 } : retail.floorStage === 'Convenience Store' ? { stage: 'Supermarket' as const, capacity: 50000, cost: 75000 } : null; if (!next) return Alert.alert('Maximum stage reached', 'Supermarket is the final warehouse stage in this release.'); if (cash < next.cost) return Alert.alert('Insufficient cash', `This upgrade requires ${formatCurrency(next.cost)}.`); if (retail.stockUnits > next.capacity) return Alert.alert('Capacity migration blocked', 'Current inventory exceeds the target warehouse capacity.'); onCashChange(value => value - next.cost); onChange({ ...business, stage: business.stage + 1, stageName: next.stage, operationalLog: [`[Expansion] - ${formatCurrency(next.cost)} · ${next.stage} opened with ${next.capacity.toLocaleString()} unit capacity.`, ...business.operationalLog].slice(0, 5), resources: { ...retail, floorStage: next.stage, maxCapacity: next.capacity } }); };
  const campaign = (cost: number, footfall: number, label: string) => { if (!retail) return; if (cash < cost) return Alert.alert('Insufficient cash', `${label} requires ${formatCurrency(cost)}.`); onCashChange(value => value - cost); onChange({ ...business, resources: { ...retail, customerFootfallPerHour: retail.customerFootfallPerHour + footfall }, operationalLog: [`[Growth] - ${formatCurrency(cost)} · ${label} added +${footfall} footfall/hr.`, ...business.operationalLog].slice(0, 5) }); };
  return <SafeAreaView edges={['top', 'left', 'right']} style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>CAPITAL / EXPANSION</Text><Text style={styles.title}>Scale the footprint</Text><Text style={styles.subtitle}>Expand only when the warehouse and wallet can support the next operating stage.</Text>{retail ? <><View style={styles.card}><Text style={styles.cardTitle}>STORE UPGRADE PATH</Text><Metric label="Current stage" value={`${retail.floorStage} · ${getWarehouseCapacity(retail).toLocaleString()} units`} /><Action title={retail.floorStage === 'Corner Kiosk' ? 'UPGRADE TO CONVENIENCE STORE' : retail.floorStage === 'Convenience Store' ? 'UPGRADE TO SUPERMARKET' : 'MAXIMUM STAGE REACHED'} copy={retail.floorStage === 'Corner Kiosk' ? '$15,000 · warehouse expands to 10,000 units' : retail.floorStage === 'Convenience Store' ? '$75,000 · warehouse expands to 50,000 units' : 'No further warehouse upgrade is available.'} onPress={upgrade} disabled={retail.floorStage === 'Supermarket'}/></View><View style={styles.card}><Text style={styles.cardTitle}>MARKETING & PR DEPARTMENT</Text><Action title="SOCIAL MEDIA CAMPAIGN" copy="$1,000 · +250 footfall/hr" onPress={() => campaign(1000, 250, 'Social Media Campaign')} /><Action title="CITY RADIO AD" copy="$5,000 · +800 footfall/hr" onPress={() => campaign(5000, 800, 'City Radio Ad')} /></View></> : <Text style={styles.muted}>Expansion controls are currently configured for retail operations.</Text>}</ScrollView></SafeAreaView>;
}
function Metric({ label, value }: { label: string; value: string }) { return <View style={styles.metric}><Text style={styles.muted}>{label}</Text><Text style={styles.metricValue}>{value}</Text></View>; }
function Action({ title, copy, onPress, disabled = false }: { title: string; copy: string; onPress: () => void; disabled?: boolean }) { return <Pressable disabled={disabled} onPress={onPress} style={[styles.action, disabled && styles.disabled]}><Text style={styles.actionTitle}>{title}</Text><Text style={styles.muted}>{copy}</Text></Pressable>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: C.bg }, content: { padding: 20, paddingBottom: 120 }, eyebrow: { color: C.cyan, fontSize: 11, fontWeight: '800', letterSpacing: 1.5 }, title: { color: C.text, fontSize: 30, fontWeight: '900', marginTop: 8 }, subtitle: { color: C.muted, lineHeight: 21, marginTop: 8, marginBottom: 20 }, card: { backgroundColor: C.panel, borderRadius: 20, padding: 18, marginBottom: 16, borderWidth: 1, borderColor: C.slate }, cardTitle: { color: C.text, fontWeight: '900', letterSpacing: 1, marginBottom: 12 }, metric: { paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: C.slate }, metricValue: { color: C.text, fontSize: 18, fontWeight: '800', marginTop: 4 }, action: { padding: 15, backgroundColor: '#182231', borderRadius: 14, marginTop: 10 }, actionTitle: { color: C.green, fontWeight: '900', marginBottom: 5 }, muted: { color: C.muted, fontSize: 12, lineHeight: 18 }, disabled: { opacity: .5 } });
export default BusinessExpansionScreen;
