import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { BusinessEntity } from '../types/game';
import { calculateHourlyProfit } from '../engine/businessEngine';
import { formatCurrency } from '../utils/formatCurrency';
import { BusinessStackParamList } from './businessNavigation';
const C = { bg: '#0B0F17', panel: '#121923', green: '#00E676', cyan: '#00D2FF', text: '#F7FAFC', muted: '#8190A5', slate: '#1E293B' };
type Props = NativeStackScreenProps<BusinessStackParamList, 'BusinessDetail'>;
export function BusinessDetailScreen({ route, navigation }: Props) {
  const { business } = route.params;
  const profit = calculateHourlyProfit(business);
  const open = (screen: 'BusinessFinancials' | 'BusinessSupplyChain' | 'BusinessWorkforce' | 'BusinessExpansion') => navigation.navigate(screen, route.params);
  return <SafeAreaView edges={['top', 'left', 'right']} style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => navigation.goBack()}><Text style={styles.back}>‹ BUSINESS REGISTRY</Text></Pressable><Text style={styles.eyebrow}>{business.sector.toUpperCase()} CONTROL CENTER</Text><Text style={styles.title}>{business.registeredName || business.name}</Text><Text style={styles.subtitle}>Executive command layer · {business.stageName}</Text><View style={styles.hero}><Text style={styles.heroIcon}>{business.icon}</Text><View><Text style={styles.muted}>NET OPERATING PROFIT</Text><Text style={styles.heroValue}>{formatCurrency(profit)}/HR</Text><Text style={styles.muted}>{business.operatingMode === 'Licensed_Legal' ? 'LICENSED LEGAL' : 'SHADOW UNDERGROUND'} · {business.stabilityIndex.toFixed(0)}% stability</Text></View></View><Text style={styles.section}>EXECUTIVE MODULES</Text><ExecutiveCard title="FINANCIALS" copy="P&L statement and last 20 auditable transactions." onPress={() => open('BusinessFinancials')} color={C.green} /><ExecutiveCard title="SUPPLY CHAIN" copy="Warehouse capacity, supplier tiers, and safe auto-restock." onPress={() => open('BusinessSupplyChain')} color={C.cyan} /><ExecutiveCard title="WORKFORCE" copy="Staff roster, general manager automation, and morale." onPress={() => open('BusinessWorkforce')} color="#E6B86A" /><ExecutiveCard title="EXPANSION" copy="Store upgrades, warehouse growth, and marketing." onPress={() => open('BusinessExpansion')} color="#A78BFA" /></ScrollView></SafeAreaView>;
}
function ExecutiveCard({ title, copy, onPress, color }: { title: string; copy: string; onPress: () => void; color: string }) { return <Pressable onPress={onPress} style={styles.module}><View style={[styles.moduleAccent, { backgroundColor: color }]} /><View style={{ flex: 1 }}><Text style={[styles.moduleTitle, { color }]}>{title}</Text><Text style={styles.muted}>{copy}</Text></View><Text style={styles.chevron}>›</Text></Pressable>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: C.bg }, content: { padding: 20, paddingBottom: 120 }, back: { color: C.cyan, fontWeight: '800', marginBottom: 24 }, eyebrow: { color: C.cyan, fontSize: 11, fontWeight: '800', letterSpacing: 1.5 }, title: { color: C.text, fontSize: 30, fontWeight: '900', marginTop: 8 }, subtitle: { color: C.muted, marginTop: 8, marginBottom: 20 }, hero: { flexDirection: 'row', alignItems: 'center', backgroundColor: C.panel, borderRadius: 20, padding: 18, borderWidth: 1, borderColor: C.slate, marginBottom: 28 }, heroIcon: { color: C.green, fontSize: 38, marginRight: 15 }, heroValue: { color: C.green, fontSize: 26, fontWeight: '900', marginVertical: 4 }, muted: { color: C.muted, fontSize: 12, lineHeight: 18 }, section: { color: C.text, fontWeight: '900', letterSpacing: 1, marginBottom: 12 }, module: { flexDirection: 'row', alignItems: 'center', backgroundColor: C.panel, borderRadius: 18, padding: 17, marginBottom: 12, borderWidth: 1, borderColor: C.slate }, moduleAccent: { width: 5, height: 48, borderRadius: 4, marginRight: 14 }, moduleTitle: { fontWeight: '900', letterSpacing: 1, marginBottom: 5 }, chevron: { color: C.text, fontSize: 28, marginLeft: 10 } });
export default BusinessDetailScreen;
