import React, { useMemo } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { BusinessEntity } from '../types/game';
import { getRetailUnitEconomics, getWarehouseCapacity, getWarehouseStage } from '../engine/businessEngine';
import { formatCurrency } from '../utils/formatCurrency';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { BusinessStackParamList } from './businessNavigation';
const C = { bg: '#0B0F17', panel: '#121923', green: '#00E676', red: '#FF3D71', cyan: '#00D2FF', text: '#F7FAFC', muted: '#8190A5', slate: '#1E293B', gold: '#E6B86A' };
export function BusinessSupplyChainScreen({ route }: NativeStackScreenProps<BusinessStackParamList, 'BusinessSupplyChain'>) {
  const { business, cash, onCashChange, onChange } = route.params;
  const retail = business.resources.kind === 'retail' ? business.resources : null;
  const capacity = retail ? getWarehouseCapacity(retail) : 0;
  const economics = retail ? getRetailUnitEconomics(retail) : null;
  const suppliers = retail ? [{ tier: 'Tier 1 · Local Distributor', units: 500, unitCost: 3 }, { tier: 'Tier 2 · Regional Wholesale', units: 2500, unitCost: 2.5 }, { tier: 'Tier 3 · Factory Direct', units: 10000, unitCost: 2 }] : [];
  const ratio = retail && capacity ? Math.min(1, retail.stockUnits / capacity) : 0;
  const order = (units: number, unitCost: number) => {
    if (!retail) return;
    const available = capacity - retail.stockUnits;
    if (available < units) return Alert.alert('WAREHOUSE AT MAX CAPACITY', `${retail.stockUnits.toLocaleString()} / ${capacity.toLocaleString()} units stored. Expand floor space to store more.`);
    const total = units * unitCost;
    if (cash < total) return Alert.alert('Insufficient cash', `This supplier order requires ${formatCurrency(total)}.`);
    const next = { ...business, resources: { ...retail, stockUnits: retail.stockUnits + units }, operationalLog: [`[Restock] - ${formatCurrency(total)} · Ordered ${units.toLocaleString()} units @ ${formatCurrency(unitCost)}/ea`, ...business.operationalLog].slice(0, 5), transactionLedger: [{ id: `restock-${Date.now()}`, at: Date.now(), type: 'restock' as const, amount: -total, label: `[Restock] Ordered ${units.toLocaleString()} units @ ${formatCurrency(unitCost)}/ea` }, ...(business.transactionLedger || [])].slice(0, 20) };
    onCashChange(value => value - total); onChange(next);
  };
  const setAuto = (value: boolean) => { if (!retail) return; onChange({ ...business, resources: { ...retail, autoOrderWhenLow: value } }); };
  return <SafeAreaView edges={['top', 'left', 'right']} style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>OPERATIONS / SUPPLY CHAIN</Text><Text style={styles.title}>Warehouse control</Text><Text style={styles.subtitle}>Every order is capacity-checked before cash leaves the wallet.</Text>{retail ? <><View style={styles.card}><View style={styles.row}><Text style={styles.cardTitle}>WAREHOUSE CAPACITY</Text><Text style={styles.capacity}>{retail.stockUnits.toLocaleString()} / {capacity.toLocaleString()}</Text></View><View style={styles.track}><View style={[styles.fill, { width: `${ratio * 100}%`, backgroundColor: ratio >= .9 ? C.red : C.green }]} /></View><Text style={ratio >= 1 ? styles.warning : styles.muted}>{ratio >= 1 ? 'WAREHOUSE AT MAX CAPACITY · Expand floor space to store more.' : `${Math.round(ratio * 100)}% utilized · ${getWarehouseStage(retail)} stage`}</Text></View><View style={styles.card}><Text style={styles.cardTitle}>UNIT ECONOMICS</Text><Metric label="Selling price" value={`${formatCurrency(economics!.sellingPrice)} / unit`} /><Metric label="Current wholesale basis" value={`${formatCurrency(economics!.unitWholesaleCost)} / unit`} /><Metric label="Margin" value={`${retail.profitMarginPercent}%`} /></View><View style={styles.card}><Text style={styles.cardTitle}>SUPPLIER TIERS</Text>{suppliers.map(supplier => { const full = retail.stockUnits + supplier.units > capacity; return <Pressable key={supplier.tier} disabled={full} onPress={() => order(supplier.units, supplier.unitCost)} style={[styles.supplier, full && styles.disabled]}><View style={{ flex: 1 }}><Text style={styles.supplierTitle}>{supplier.tier}</Text><Text style={styles.muted}>{supplier.units.toLocaleString()} units @ {formatCurrency(supplier.unitCost)}/unit</Text>{full && <Text style={styles.warning}>LOCKED · capacity available: {Math.max(0, capacity - retail.stockUnits).toLocaleString()}</Text>}</View><Text style={full ? styles.locked : styles.buy}>{formatCurrency(supplier.units * supplier.unitCost)}</Text></Pressable>; })}</View><View style={styles.card}><View style={styles.row}><View style={{ flex: 1 }}><Text style={styles.cardTitle}>SMART AUTO-RESTOCK</Text><Text style={styles.muted}>Only orders when stock is below the threshold, cash covers the batch, and the warehouse can fit it.</Text></View><Switch value={retail.autoOrderWhenLow} onValueChange={setAuto} trackColor={{ false: C.slate, true: '#087C4A' }} thumbColor={retail.autoOrderWhenLow ? C.green : C.muted} /></View></View></> : <Text style={styles.muted}>Supply-chain controls are available for retail businesses.</Text>}</ScrollView></SafeAreaView>;
}
function Metric({ label, value }: { label: string; value: string }) { return <View style={styles.metric}><Text style={styles.muted}>{label}</Text><Text style={styles.metricValue}>{value}</Text></View>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: C.bg }, content: { padding: 20, paddingBottom: 120 }, eyebrow: { color: C.cyan, fontSize: 11, fontWeight: '800', letterSpacing: 1.5 }, title: { color: C.text, fontSize: 30, fontWeight: '900', marginTop: 8 }, subtitle: { color: C.muted, lineHeight: 21, marginTop: 8, marginBottom: 20 }, card: { backgroundColor: C.panel, borderRadius: 20, padding: 18, marginBottom: 16, borderWidth: 1, borderColor: C.slate }, cardTitle: { color: C.text, fontWeight: '900', letterSpacing: 1, marginBottom: 10 }, row: { flexDirection: 'row', alignItems: 'center' }, capacity: { color: C.cyan, fontWeight: '900' }, track: { height: 12, backgroundColor: C.slate, borderRadius: 8, overflow: 'hidden', marginVertical: 12 }, fill: { height: '100%', borderRadius: 8 }, muted: { color: C.muted, fontSize: 12, lineHeight: 18 }, warning: { color: C.red, fontSize: 12, lineHeight: 18, marginTop: 6 }, metric: { paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: C.slate }, metricValue: { color: C.text, fontSize: 18, fontWeight: '800', marginTop: 4 }, supplier: { flexDirection: 'row', alignItems: 'center', paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: C.slate }, supplierTitle: { color: C.text, fontWeight: '800' }, buy: { color: C.green, fontWeight: '900' }, locked: { color: C.red, fontWeight: '800', fontSize: 11 }, disabled: { opacity: .55 } });
export default BusinessSupplyChainScreen;
