import * as Haptics from 'expo-haptics';
import React, { useCallback, useEffect, useRef, useState } from 'react';
import { Animated as RNAnimated, Pressable, StyleSheet, Text, View } from 'react-native';
import { WealthCard } from '../components/WealthCard';
import { formatCurrency } from '../utils/formatCurrency';

type BadgeItem = { id: number; amount: number };
type HomeScreenProps = { cash: number; netWorth: number; clickValue: number; clickLevel: number; clickUpgradeCost: number; onEarn: (amount: number) => void; onUpgrade: () => void; onOpenBusiness: () => void; onOpenStore: () => void };

export function HomeScreen({ cash, netWorth, clickValue, clickLevel, clickUpgradeCost, onEarn, onUpgrade, onOpenBusiness, onOpenStore }: HomeScreenProps) {
  const [badges, setBadges] = useState<BadgeItem[]>([]); const nextId = useRef(0);
  const tap = useCallback(() => { void Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light); const id = nextId.current++; setBadges(current => [...current.slice(-5), { id, amount: clickValue }]); onEarn(clickValue); }, [clickValue, onEarn]);
  return <View style={styles.root}>
    <View><Text style={styles.eyebrow}>HOME / CLICKER</Text><Text style={styles.title}>Build your fortune.</Text><WealthCard cash={cash} netWorth={netWorth} /></View>
    <View style={styles.upgradeRow}><View style={styles.upgradeCopy}><Text style={styles.muted}>CURRENT PER CLICK</Text><Text style={styles.current}>{formatCurrency(clickValue)}</Text><Text style={styles.level}>LEVEL {clickLevel} · +$0.50 NEXT</Text></View><Pressable disabled={clickValue >= 10} onPress={onUpgrade} style={({ pressed }) => [styles.upgrade, pressed && styles.pressed, clickValue >= 10 && styles.disabled]}><Text style={styles.upgradeText}>{clickValue >= 10 ? 'MAX $10.00' : `UPGRADE ${formatCurrency(clickUpgradeCost)}`}</Text></Pressable></View>
    <View style={styles.progress}><View style={[styles.progressFill, { width: `${(clickValue / 10) * 100}%` }]} /></View>
    <View style={styles.tapSection}><Text style={styles.tapTitle}>TAP TO EARN</Text><Text style={styles.tapSub}>Each tap adds {formatCurrency(clickValue)} to liquid cash.</Text><View style={styles.badges}>{badges.map(item => <FloatingBadge key={item.id} amount={item.amount} onDone={() => setBadges(current => current.filter(badge => badge.id !== item.id))} />)}</View><Pressable onPress={tap} style={({ pressed }) => [styles.tap, pressed && styles.tapPressed]}><Text style={styles.tapAmount}>+{formatCurrency(clickValue)}</Text><Text style={styles.tapLabel}>TAP</Text></Pressable></View>
    <View style={styles.links}><Pressable onPress={onOpenBusiness} style={styles.link}><Text style={styles.linkTitle}>RETAIL SHOP</Text><Text style={styles.muted}>Operate your enterprise</Text></Pressable><Pressable onPress={onOpenStore} style={styles.link}><Text style={styles.linkTitle}>BANK / STORE</Text><Text style={styles.muted}>Founder packs & upgrades</Text></Pressable></View>
  </View>;
}
function FloatingBadge({ amount, onDone }: { amount: number; onDone: () => void }) { const translateY = useRef(new RNAnimated.Value(0)).current; const opacity = useRef(new RNAnimated.Value(1)).current; useEffect(() => { RNAnimated.parallel([RNAnimated.timing(translateY, { toValue: -60, duration: 700, useNativeDriver: true }), RNAnimated.timing(opacity, { toValue: 0, duration: 700, useNativeDriver: true })]).start(({ finished }) => { if (finished) onDone(); }); }, [onDone, opacity, translateY]); return <RNAnimated.Text style={[styles.badge, { transform: [{ translateY }], opacity }]}>+{formatCurrency(amount)}</RNAnimated.Text>; }
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: '#0B0F17', paddingHorizontal: 16, justifyContent: 'space-between', paddingBottom: 8 }, eyebrow: { color: '#00D2FF', fontSize: 10, fontWeight: '900', letterSpacing: 2 }, title: { color: '#F7FAFC', fontSize: 24, fontWeight: '900', marginVertical: 6 }, upgradeRow: { height: 64, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#121923', borderRadius: 14, paddingHorizontal: 14, borderWidth: 1, borderColor: '#1E293B' }, upgradeCopy: { flex: 1 }, muted: { color: '#8190A5', fontSize: 11 }, current: { color: '#00E676', fontSize: 18, fontWeight: '900', marginVertical: 1 }, level: { color: '#8190A5', fontSize: 9, fontWeight: '800' }, upgrade: { backgroundColor: '#00E676', borderRadius: 10, paddingHorizontal: 12, paddingVertical: 10, maxWidth: 145 }, upgradeText: { color: '#0B0F17', fontSize: 10, fontWeight: '900', textAlign: 'center' }, disabled: { backgroundColor: '#334155' }, pressed: { opacity: .75 }, progress: { height: 6, backgroundColor: '#1E293B', borderRadius: 8, overflow: 'hidden', marginTop: -8 }, progressFill: { height: '100%', backgroundColor: '#00E676' }, tapSection: { backgroundColor: '#121923', borderRadius: 18, padding: 12, alignItems: 'center', marginTop: 2 }, tapTitle: { color: '#F7FAFC', fontSize: 12, fontWeight: '900', letterSpacing: 1 }, tapSub: { color: '#8190A5', fontSize: 10, marginTop: 3 }, tap: { width: 138, height: 138, borderRadius: 69, backgroundColor: '#00E676', justifyContent: 'center', alignItems: 'center', marginTop: 8, shadowColor: '#00E676', shadowOpacity: .35, shadowRadius: 18, elevation: 8 }, tapPressed: { transform: [{ scale: .96 }] }, tapAmount: { color: '#0B0F17', fontSize: 21, fontWeight: '900' }, tapLabel: { color: '#0B0F17', fontSize: 10, fontWeight: '900', letterSpacing: 2, marginTop: 2 }, badges: { height: 0, position: 'relative', zIndex: 2 }, badge: { color: '#00E676', fontSize: 17, fontWeight: '900', position: 'absolute', width: 180, textAlign: 'center', top: 10 }, links: { flexDirection: 'row', gap: 10, marginTop: 2 }, link: { flex: 1, backgroundColor: '#182231', borderRadius: 12, padding: 10 }, linkTitle: { color: '#E6B86A', fontSize: 10, fontWeight: '900', marginBottom: 3 } });
