import React, { useMemo } from 'react';
import { FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import Svg, { Defs, LinearGradient, Path, Stop } from 'react-native-svg';

type Asset = { id: string; symbol: string; name: string; kind: 'STOCK' | 'CRYPTO'; price: number; change: number; dividend: number; volatility: number; history: number[] };
type Holding = { shares: number; avgPrice: number; realized: number };
type Filter = 'dividend' | 'cheap' | 'crypto' | 'all';
const C = { panel: '#121923', panel2: '#182231', green: '#00E676', red: '#FF3D71', cyan: '#00D2FF', text: '#F7FAFC', muted: '#8190A5', slate: '#1E293B' };
const money = (n: number) => `$${Math.max(0, n).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const short = (n: number) => Math.abs(n) >= 1e6 ? `$${(n / 1e6).toFixed(2)}M` : Math.abs(n) >= 1e3 ? `$${(n / 1e3).toFixed(2)}K` : money(n);
const pct = (n: number) => `${n >= 0 ? '+' : ''}${n.toFixed(2)}%`;

export function MarketScreen({ assets, holdings, filter, setFilter, trade, unrealized, positionsValue }: { assets: Asset[]; holdings: Record<string, Holding>; filter: Filter; setFilter: (f: Filter) => void; trade: (asset: Asset, buy: boolean) => void; unrealized: number; positionsValue: number }) {
  const visible = useMemo(() => assets.filter(asset => filter === 'crypto' ? asset.kind === 'CRYPTO' : filter === 'cheap' ? asset.price < 1000 : filter === 'dividend' ? asset.dividend > 1 : true), [assets, filter]);
  return <View style={styles.screen}><Text style={styles.eyebrow}>STOCK & CRYPTO MARKETS</Text><Text style={styles.title}>Professional trading</Text><View style={styles.portStrip}><View><Text style={styles.muted}>TOTAL POSITION VALUE</Text><Text style={styles.portTotal}>{short(positionsValue)}</Text></View><View><Text style={unrealized >= 0 ? styles.up : styles.down}>P&L {money(unrealized)}</Text><Text style={styles.muted}>LIVE MARK TO MARKET</Text></View></View><View style={styles.filterRail}>{(['all', 'dividend', 'cheap', 'crypto'] as Filter[]).map(value => <Pressable key={value} onPress={() => setFilter(value)} style={[styles.filter, filter === value && styles.filterOn]}><Text style={[styles.filterText, filter === value && styles.filterTextOn]}>{value === 'all' ? 'ALL ASSETS' : value === 'dividend' ? 'DIVIDEND' : value === 'cheap' ? 'CHEAPEST' : 'CRYPTO'}</Text></Pressable>)}</View><FlatList data={visible} keyExtractor={asset => asset.id} renderItem={({ item }) => <MarketRow asset={item} holding={holdings[item.id]} trade={trade} />} contentContainerStyle={styles.listContent} showsVerticalScrollIndicator={false} /></View>;
}
function MarketRow({ asset, holding, trade }: { asset: Asset; holding?: Holding; trade: (asset: Asset, buy: boolean) => void }) {
  return <View style={styles.card}><View style={styles.leftColumn}><View style={styles.badge}><Text style={styles.badgeText}>{asset.symbol.slice(0, 3)}</Text></View><Text style={styles.name} numberOfLines={1}>{asset.name}</Text><Text style={styles.muted}>{holding?.shares || 0} shares</Text></View><View style={styles.centerColumn}><Sparkline points={asset.history.slice(-15)} positive={asset.change >= 0} /></View><View style={styles.rightColumn}><Text style={styles.price} numberOfLines={1}>{short(asset.price)}</Text><Text style={asset.change >= 0 ? styles.up : styles.down}>{pct(asset.change)}</Text><View style={styles.tradeRow}><Pressable accessibilityLabel={`Sell ${asset.symbol}`} onPress={() => trade(asset, false)} style={styles.sell}><Text style={styles.sellText}>SELL</Text></Pressable><Pressable accessibilityLabel={`Buy ${asset.symbol}`} onPress={() => trade(asset, true)} style={styles.buy}><Text style={styles.buyText}>BUY</Text></Pressable></View></View></View>;
}
function Sparkline({ points, positive }: { points: number[]; positive: boolean }) { const width = 100; const height = 42; const min = Math.min(...points); const max = Math.max(...points); const line = points.map((point, index) => `${index ? 'L' : 'M'}${(index / Math.max(1, points.length - 1)) * width},${height - ((point - min) / Math.max(1, max - min)) * 30 - 5}`).join(' '); const area = `${line} L${width},${height} L0,${height} Z`; const color = positive ? C.green : C.red; const gradientId = `market-fill-${positive ? 'up' : 'down'}`; return <Svg width={width} height={height}><Defs><LinearGradient id={gradientId} x1="0" y1="0" x2="0" y2="1"><Stop offset="0" stopColor={color} stopOpacity=".3" /><Stop offset="1" stopColor={color} stopOpacity="0" /></LinearGradient></Defs><Path d={area} fill={`url(#${gradientId})`} /><Path d={line} fill="none" stroke={color} strokeWidth="2" /></Svg>; }
const styles = StyleSheet.create({ screen: { flex: 1, minWidth: 0 }, eyebrow: { color: C.cyan, fontSize: 10, fontWeight: '900', letterSpacing: 2 }, title: { color: C.text, fontSize: 29, fontWeight: '900', marginVertical: 8 }, muted: { color: C.muted, fontSize: 11 }, portStrip: { backgroundColor: C.panel, borderRadius: 14, padding: 14, flexDirection: 'row', justifyContent: 'space-between', marginTop: 10 }, portTotal: { color: C.text, fontSize: 22, fontWeight: '900', marginTop: 4 }, up: { color: C.green, fontSize: 11, fontWeight: '900' }, down: { color: C.red, fontSize: 11, fontWeight: '900' }, filterRail: { flexDirection: 'row', gap: 7, marginVertical: 10 }, filter: { flex: 1, minWidth: 0, paddingVertical: 9, borderRadius: 9, backgroundColor: C.panel, borderWidth: 1, borderColor: C.slate, alignItems: 'center' }, filterOn: { backgroundColor: '#123D34', borderColor: C.green }, filterText: { color: C.muted, fontSize: 8, fontWeight: '900' }, filterTextOn: { color: C.green }, listContent: { paddingHorizontal: 16, paddingBottom: 100, gap: 8 }, card: { alignSelf: 'stretch', minWidth: 0, backgroundColor: C.panel, borderRadius: 14, borderWidth: 1, borderColor: C.slate, padding: 10, flexDirection: 'row', alignItems: 'center' }, leftColumn: { flexBasis: '30%', flexGrow: 0, flexShrink: 1, minWidth: 0, paddingRight: 6 }, centerColumn: { flexBasis: '35%', flexGrow: 0, flexShrink: 1, minWidth: 0, alignItems: 'center' }, rightColumn: { flexBasis: '35%', flexGrow: 0, flexShrink: 1, minWidth: 0, alignItems: 'flex-end', paddingLeft: 5 }, badge: { width: 34, height: 34, borderRadius: 10, backgroundColor: '#20334B', justifyContent: 'center', alignItems: 'center', marginBottom: 5 }, badgeText: { color: C.cyan, fontSize: 8, fontWeight: '900' }, name: { color: C.text, fontSize: 11, fontWeight: '900' }, price: { color: C.text, fontSize: 12, fontWeight: '900', maxWidth: '100%' }, tradeRow: { flexDirection: 'row', gap: 4, marginTop: 7 }, sell: { backgroundColor: '#252A36', borderRadius: 6, paddingVertical: 6, paddingHorizontal: 7 }, buy: { backgroundColor: C.green, borderRadius: 6, paddingVertical: 6, paddingHorizontal: 7 }, sellText: { color: C.text, fontSize: 8, fontWeight: '900' }, buyText: { color: '#0B0F17', fontSize: 8, fontWeight: '900' } });
