import React, { useEffect, useMemo, useState } from 'react';
import { Alert, Pressable, Text, View } from 'react-native';
import { formatCurrency } from '../utils/formatCurrency';
const duration = { Governor_Maryland: 30, President_USA: 45 } as const;
export function PoliticsScreen({ cash, setCash, office, setOffice }: { cash: number; setCash: React.Dispatch<React.SetStateAction<number>>; office: 'Citizen' | 'Governor_Maryland' | 'President_USA'; setOffice: (o: 'Citizen' | 'Governor_Maryland' | 'President_USA') => void }) {
  const [seasonStarted] = useState(Date.now()); const [now, setNow] = useState(Date.now()); const [race, setRace] = useState<'Governor_Maryland' | 'President_USA'>('Governor_Maryland'); const [votes, setVotes] = useState(0);
  useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, []);
  const ends = seasonStarted + duration[race] * 86400000; const remain = Math.max(0, ends - now); const days = Math.floor(remain / 86400000); const hours = Math.floor(remain / 3600000) % 24; const minutes = Math.floor(remain / 60000) % 60; const seconds = Math.floor(remain / 1000) % 60;
  const campaign = (cost: number, gain: number) => { if (cash < cost) return Alert.alert('War chest shortfall', `Need ${formatCurrency(cost)}.`); setCash(v => v - cost); setVotes(v => v + gain); };
  const win = () => { if (votes < (race === 'Governor_Maryland' ? 5000 : 15000)) return Alert.alert('Election not won', 'Increase your voter influence first.'); setOffice(race); Alert.alert('Election victory', race === 'Governor_Maryland' ? 'Governor office unlocked: 5% corporate tax reduction.' : 'President office unlocked: presidential fleet and shadow-raid immunity.'); };
  return <View><Text style={{ color: '#00D2FF', fontSize: 10, fontWeight: '900', letterSpacing: 2 }}>GEOPOLITICAL WAR ROOM</Text><Text style={{ color: '#F7FAFC', fontSize: 28, fontWeight: '900', marginVertical: 8 }}>Election cycles</Text><View style={{ flexDirection: 'row', gap: 8 }}><Pressable onPress={() => setRace('Governor_Maryland')}><Text style={{ color: race === 'Governor_Maryland' ? '#00E676' : '#8190A5' }}>MARYLAND GOVERNOR</Text></Pressable><Pressable onPress={() => setRace('President_USA')}><Text style={{ color: race === 'President_USA' ? '#00E676' : '#8190A5' }}>PRESIDENT USA</Text></Pressable></View><Text style={{ color: '#F7FAFC', fontSize: 34, fontWeight: '900', marginTop: 24 }}>{String(days).padStart(2, '0')} : {String(hours).padStart(2, '0')} : {String(minutes).padStart(2, '0')} : {String(seconds).padStart(2, '0')}</Text><Text style={{ color: '#8190A5', marginTop: 6 }}>UTC synchronized · {duration[race]} real days · current office: {office}</Text><Text style={{ color: '#00E676', fontSize: 19, fontWeight: '900', marginTop: 22 }}>Influence votes: {votes.toLocaleString('en-US')}</Text>{[[50000, 500, 'TV & social attack ads'], [200000, 2500, 'Donor gala dinner'], [1000000, 15000, 'Corporate Super PAC lobby']].map(([cost, gain, label]) => <Pressable key={String(cost)} onPress={() => campaign(Number(cost), Number(gain))} style={{ backgroundColor: '#121923', padding: 15, borderRadius: 12, marginTop: 10 }}><Text style={{ color: '#F7FAFC', fontWeight: '900' }}>{label}</Text><Text style={{ color: '#8190A5', marginTop: 5 }}>{formatCurrency(Number(cost))} · +{gain} votes</Text></Pressable>)}<Pressable onPress={win} style={{ backgroundColor: '#00E676', padding: 15, borderRadius: 12, marginTop: 15 }}><Text style={{ color: '#0B0F17', textAlign: 'center', fontWeight: '900' }}>DECLARE VICTORY</Text></Pressable></View>;
}
