import React, { useState } from 'react';
import { Alert, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import Svg, { Path } from 'react-native-svg';
import { technicalSnapshot } from '../engine/marketIntelligenceEngine';
import { Asset } from '../types/marketAsset';
import { PriceAlert, PriceAlertCondition } from '../types/marketIntelligence';

const C = { bg: '#0B0F17', panel: '#14243A', panel2: '#0D241A', green: '#16E98A', red: '#FF6D62', cyan: '#61E8FF', gold: '#FFC928', text: '#F7FFF9', muted: '#8FB5A4', slate: '#236A45' };
const money = (n: number) => `$${n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

export function TechnicalChartModal({ visible, asset, priceAlerts, onClose, onCreateAlert }: { visible: boolean; asset: Asset; priceAlerts: PriceAlert[]; onClose: () => void; onCreateAlert: (alert: PriceAlert) => void }) {
  const [condition, setCondition] = useState<PriceAlertCondition>('ABOVE');
  const [target, setTarget] = useState(String(asset.price.toFixed(2)));
  const values = asset.history.slice(-60); const snapshot = technicalSnapshot(asset.history); const width = 330; const height = 110; const min = Math.min(...values); const max = Math.max(...values); const scale = Math.max(0.0001, max - min);
  const line = values.map((value, index) => `${index ? 'L' : 'M'}${(index / Math.max(1, values.length - 1)) * width},${height - ((value - min) / scale) * 82 - 10}`).join(' ');
  const addAlert = () => { const value = Number(target); if (!Number.isFinite(value) || value <= 0) return Alert.alert('ALERT NOT SET', 'Enter a positive target.'); onCreateAlert({ id: `alert-${Date.now()}-${asset.id}`, assetId: asset.id, symbol: asset.symbol, name: asset.name, condition, target: value, baselinePrice: asset.price, enabled: true, createdAt: Date.now() }); Alert.alert('PRICE ALERT SET', `${asset.symbol} alert will evaluate on every market tick.`); };
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.shade}><View style={styles.modal}><View style={styles.head}><View><Text style={styles.eyebrow}>TECHNICAL DESK</Text><Text style={styles.title}>{asset.symbol} · {asset.name}</Text></View><Pressable onPress={onClose}><Text style={styles.close}>×</Text></Pressable></View><View style={styles.legend}><Text style={styles.price}>PRICE</Text><Text style={styles.sma}>SMA20 {snapshot.sma20 ? money(snapshot.sma20) : '—'}</Text><Text style={styles.ema}>EMA12 {snapshot.ema12 ? money(snapshot.ema12) : '—'}</Text></View><Svg width="100%" height={height} viewBox={`0 0 ${width} ${height}`}><Path d={line} fill="none" stroke={asset.change >= 0 ? C.green : C.red} strokeWidth="2.5" /></Svg><View style={styles.grid}>{[['RSI 14', snapshot.rsi14], ['MACD', snapshot.macd], ['SIGNAL', snapshot.signal9], ['TREND', snapshot.trend]].map(([label, value]) => <View key={String(label)} style={styles.cell}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value === null ? '—' : typeof value === 'number' ? value.toFixed(2) : value}</Text></View>)}</View><Text style={styles.inputLabel}>REAL-TIME PRICE ALERT</Text><View style={styles.conditions}>{(['ABOVE', 'BELOW', 'PCT_MOVE'] as PriceAlertCondition[]).map(value => <Pressable key={value} onPress={() => setCondition(value)} style={[styles.condition, condition === value && styles.selected]}><Text style={styles.conditionText}>{value === 'PCT_MOVE' ? 'MOVE %' : value}</Text></Pressable>)}</View><TextInput value={target} onChangeText={setTarget} keyboardType="decimal-pad" style={styles.input} placeholder={condition === 'PCT_MOVE' ? 'Percent move' : 'Target price'} placeholderTextColor={C.muted} /><Pressable onPress={addAlert} style={styles.submit}><Text style={styles.submitText}>SET ALERT</Text></Pressable><Text style={styles.muted}>{priceAlerts.length ? `${priceAlerts.length} alert${priceAlerts.length === 1 ? '' : 's'} saved for this asset.` : 'No alerts set for this asset.'}</Text></View></View></Modal>;
}
const styles = StyleSheet.create({ shade: { flex: 1, backgroundColor: 'rgba(1,7,15,.84)', justifyContent: 'flex-end' }, modal: { backgroundColor: C.panel, borderTopLeftRadius: 24, borderTopRightRadius: 24, borderTopWidth: 1, borderColor: C.cyan, padding: 18, paddingBottom: 28 }, head: { flexDirection: 'row', justifyContent: 'space-between' }, eyebrow: { color: C.cyan, fontSize: 10, fontWeight: '900', letterSpacing: 2 }, title: { color: C.text, fontSize: 17, fontWeight: '900', marginTop: 5 }, close: { color: C.text, fontSize: 28 }, legend: { flexDirection: 'row', gap: 10, marginTop: 16, marginBottom: 5 }, price: { color: C.text, fontSize: 8, fontWeight: '900' }, sma: { color: C.gold, fontSize: 8, fontWeight: '900' }, ema: { color: C.cyan, fontSize: 8, fontWeight: '900' }, grid: { flexDirection: 'row', gap: 6, marginTop: 7 }, cell: { flex: 1, backgroundColor: C.panel2, borderRadius: 7, padding: 7 }, label: { color: C.muted, fontSize: 7, fontWeight: '900' }, value: { color: C.text, fontSize: 10, fontWeight: '900', marginTop: 3 }, inputLabel: { color: C.muted, fontSize: 8, fontWeight: '900', marginTop: 15, marginBottom: 6 }, conditions: { flexDirection: 'row', gap: 6 }, condition: { flex: 1, borderRadius: 8, padding: 10, backgroundColor: C.panel2, borderWidth: 1, borderColor: C.slate, alignItems: 'center' }, selected: { borderColor: C.green, backgroundColor: '#123D34' }, conditionText: { color: C.text, fontSize: 8, fontWeight: '900' }, input: { backgroundColor: C.panel2, borderWidth: 1, borderColor: C.slate, color: C.text, borderRadius: 9, padding: 11, marginTop: 8 }, submit: { backgroundColor: C.green, borderRadius: 11, padding: 14, alignItems: 'center', marginTop: 10 }, submitText: { color: C.bg, fontWeight: '900', fontSize: 10 }, muted: { color: C.muted, fontSize: 10, marginTop: 8 } });
