declare const require: any;
const assert = require('assert').strict;
const fs = require('fs');
const path = require('path');
import { calculateOfflineHours, calculateOfflineSeconds, MAX_OFFLINE_SECONDS } from '../src/engine/offlineEarnings';
import { SETTLEMENT_INTERVAL_MS, settleElapsedBusinessIncome } from '../src/engine/settlementEngine';
import { formatSystemDateTime, readSystemTimeMs, weekKeyFromSystemTime } from '../src/engine/realTimeEngine';
import { DEFAULT_BUSINESSES, passiveIncomeMultiplier, simulateBusinessOperations } from '../src/engine/businessSimulation';
import { DEFAULT_PROGRESSION, hydrateDailyProgress } from '../src/types/progression';
import { businessValuation, capIPOProceeds, createIPOListing, founderOwnershipFraction, getIPOEligibility } from '../src/engine/ipoEngine';
import { MARKET_EVENTS, applyMarketEvent, appendPortfolioPoint, calculateQuarterlyDividends, matchLimitOrders } from '../src/engine/marketEngine';
import { LimitOrder } from '../src/types/market';
import { tapUpgradeCost, tapUpgradeGain } from '../src/engine/tapUpgradeEngine';
import { CASINO_UNLOCK_NET_WORTH, IPO_MAX_NET_WORTH_PROCEEDS_MULTIPLE, IPO_MIN_NET_WORTH, PASSIVE_INCOME_CAP, RETAIL_ENTRY_COST, STARTING_CASH, TAP_VALUE_CAP } from '../src/engine/economyPlan';
import { GAME_SAVE_VERSION } from '../src/engine/saveMigration';

const root = process.cwd();
const read = (file: string) => fs.readFileSync(path.join(root, file), 'utf8');
const app = read('App.tsx');
const gameContext = read('src/context/GameContext.tsx');
const businessScreen = read('src/screens/BusinessScreen.tsx');
const homeScreen = read('src/screens/HomeScreen.tsx');
const registration = read('src/components/modals/BusinessRegistrationModal.tsx');
const network = read('src/context/NetworkContext.tsx');
const businessHub = read('src/screens/business/BusinessMasterHubScreen.tsx');
const ipoModal = read('src/components/modals/IPOLaunchModal.tsx');
const lifestyleScreen = read('src/screens/LifestyleScreen.tsx');
const casinoScreen = read('src/screens/CasinoScreen.tsx');
const realTimeEngine = read('src/engine/realTimeEngine.ts');
const screenBarrel = read('src/screens/index.ts');
const engineBarrel = read('src/engine/index.ts');

assert.match(app, /AsyncStorage\.getItem\(SAVE\)/, 'save/load: AsyncStorage load path missing');
assert.match(app, /JSON\.parse\(raw\)/, 'save/load: JSON parse path missing');
assert.match(app, /latestState\.current/, 'save/load: latest state snapshot missing');
assert.match(gameContext, /hydrated/, 'save/load: business hydration gate missing');
assert.equal(calculateOfflineSeconds(1000 + MAX_OFFLINE_SECONDS * 1000 * 4, 1000), MAX_OFFLINE_SECONDS, 'offline earnings: 24-hour cap failed');
assert.equal(calculateOfflineSeconds(1000, 1000 + 2 * 60 * 60 * 1000), 0, 'offline earnings: rollback failed');
assert.equal(calculateOfflineHours(2 * SETTLEMENT_INTERVAL_MS + 1, 1), 2, 'offline earnings: whole-hour settlement failed');
assert.equal(calculateOfflineHours(2 * SETTLEMENT_INTERVAL_MS + 1, 1, true), 0, 'offline earnings: tamper guard failed');
const systemNow = readSystemTimeMs();
assert.ok(Math.abs(systemNow - Date.now()) < 1000, 'clock: system timestamp must come from Date.now');
assert.equal(weekKeyFromSystemTime(Date.UTC(2026, 0, 1)), '2026-W01', 'clock: real calendar week key failed');
assert.match(formatSystemDateTime(systemNow), /\d+/, 'clock: system date formatter failed');
assert.match(app, /readSystemTimeMs\(\)/, 'clock: App must read the phone system time');
assert.match(app, /setInterval\(syncSystemTime, 1000\)/, 'clock: App system-time refresh missing');
assert.doesNotMatch(app, /gameTimeEngine|SimulatedGameTime|formatSimulatedGameTime|advanceGameTime/, 'clock: accelerated fake clock remains wired into App');
assert.match(realTimeEngine, /return Date\.now\(\)/, 'clock: real-time engine must read system time');
assert.match(app, /formatSystemDateTime\(systemTimeMs\)/, 'clock: App must render system date/time');
assert.match(app, /timeModel: "system-clock-v1"/, 'save migration: system clock marker missing');
assert.equal(GAME_SAVE_VERSION, 5, 'save migration: hourly settlement schema version missing');
assert.match(read('src/engine/saveMigration.ts'), /settlementAt/, 'save migration: settlement cursor migration missing');
assert.equal(fs.existsSync(path.join(root, 'src/engine/gameTimeEngine.ts')), false, 'clock: obsolete simulated clock file remains');
assert.match(screenBarrel, /MarketScreen/, 'architecture: Markets screen barrel export missing');
assert.match(engineBarrel, /realTimeEngine/, 'architecture: real-time engine barrel export missing');
assert.match(app, /ResponsiveMarketScreen/, 'architecture: Markets screen is not connected to App');
assert.match(app, /RetailBusinessScreen/, 'architecture: Business screen is not connected to App');
assert.match(app, /buildIncomeSources/, 'income ledger: App connection missing');
assert.match(app, /watchTapBoost/, 'tap boost: App handler connection missing');
assert.match(app, /showTestRewardedAd/, 'tap boost: rewarded-ad service connection missing');
const retail = { id: 'regression-retail', name: 'Regression Retail', sector: 'Retail' as const, isUnlocked: true, unlockNetWorthRequired: 0, isAcquired: true, acquisitionCost: 2500, legalStatus: 'Licensed_Legal' as const, policeHeat: 0, stability: 92, hourlyNetProfit: 0, stockUnits: 10, maxStockCapacity: 2500, pricingTier: 'Standard' as const, hasSecurity: false, hasManager: false, unitWholesaleCost: 2, monthlyRent: 800, monthlyPayroll: 1200 };
const retailTick = simulateBusinessOperations([retail], 2);
assert.equal((retailTick.businesses[0] as typeof retail).stockUnits, 8, 'retail: stock deduction failed');
assert.equal('cashDelta' in retailTick, false, 'business: operations must not return per-tick cash');
assert(retailTick.hourlyByBusiness['regression-retail'] > 0, 'retail: declared hourly rate missing');
assert.equal(simulateBusinessOperations([{ ...retail, stockUnits: 0 }], 2).hourlyByBusiness['regression-retail'], 0, 'retail: empty inventory must have zero settlement rate');
const settlementFixture = { ...retail, hourlyNetProfit: 500, pendingSettlementAmount: 1000, stockUnits: 10 };
const settlement = settleElapsedBusinessIncome([settlementFixture], 0, 2 * SETTLEMENT_INTERVAL_MS);
assert.equal(settlement.completedHours, 2, 'settlement: two elapsed hours were not recognized');
assert.equal(settlement.totalAmount, 1000, 'settlement: hourly amount was not credited exactly');
assert.equal(DEFAULT_BUSINESSES.length, 10, 'businesses: ten-sector catalog missing');
const expansion = DEFAULT_BUSINESSES.find(item => item.sector === 'Energy')!;
assert.equal(simulateBusinessOperations([{ ...expansion, isAcquired: true }], 2).businesses[0].isAcquired, true, 'businesses: expansion sector tick failed');
assert.doesNotMatch(businessScreen, /result\.cashDelta|onProfitChange|onIncome/, 'wallet: BusinessScreen still has a per-tick payout path');
assert.match(app, /settleElapsedBusinessIncome/, 'settlement: App hourly credit path missing');
assert.doesNotMatch(app, /setCash\([^\n]*profitRef|value \+ result\.cashDelta/, 'settlement: App still credits passive income per tick');
assert.match(app, /Math\.max\(0, n - total\)/, 'wallet: trade spend clamp missing');
const firstLogin = hydrateDailyProgress(DEFAULT_PROGRESSION, Date.UTC(2026, 0, 1));
const nextLogin = hydrateDailyProgress(firstLogin, Date.UTC(2026, 0, 2));
const missedLogin = hydrateDailyProgress(nextLogin, Date.UTC(2026, 0, 4));
assert.equal(firstLogin.loginStreak, 1, 'progression: first streak failed');
assert.equal(nextLogin.loginStreak, 2, 'progression: consecutive streak failed');
assert.equal(missedLogin.loginStreak, 1, 'progression: missed streak reset failed');
assert.match(app, /missionClaimed/, 'progression: mission state missing');
assert.ok(DEFAULT_PROGRESSION.achievements.length === 0 && DEFAULT_PROGRESSION.prestigeLevel === 0, 'progression: late-game defaults missing');
assert.match(homeScreen, /REBIRTH EMPIRE/, 'progression: prestige control missing');
assert.match(homeScreen, /WEEKLY EVENT/, 'progression: weekly event UI missing');
assert.match(homeScreen, /onOpenNextGoal/, 'goal: next-goal card is not tappable');
assert.match(app, /focusRetail/, 'goal: Retail stock-order route is not wired');
const ipoBusiness = { ...retail, baseHourlyNetProfit: 25000, hourlyNetProfit: 25000 };
assert.equal(getIPOEligibility({ ...ipoBusiness, isAcquired: false }, null, 10_000_000).eligible, false, 'IPO: unacquired company was eligible');
assert.equal(getIPOEligibility(ipoBusiness, null, 10_000_000).eligible, true, 'IPO: eligible company was blocked');
const listing = createIPOListing(ipoBusiness, Date.UTC(2026, 0, 1), 'IPO', 10_000_000);
assert.equal(getIPOEligibility(ipoBusiness, listing, 10_000_000).eligible, false, 'IPO: duplicate public offering was allowed');
const cappedListing = capIPOProceeds(createIPOListing(ipoBusiness, Date.UTC(2026, 0, 1), 'IPO', 1_000_000), 1_000_000);
assert.equal(founderOwnershipFraction(cappedListing), 0.8, 'IPO: founder ownership was not diluted to 80%');
assert(cappedListing.capitalRaised <= 500_000, 'IPO: proceeds exceeded 0.5x net worth cap');
const valuationAt10M = businessValuation(ipoBusiness, 10_000_000);
const valuationAt50M = businessValuation(ipoBusiness, 50_000_000);
assert(valuationAt10M <= 40_000_000 && valuationAt50M <= 200_000_000, 'IPO: valuation exceeded 4x net-worth cap');
assert(valuationAt50M > valuationAt10M, 'IPO: larger net-worth company valuation order inverted');
const legacyListing = capIPOProceeds({ ...listing, valuationAtIPO: 300_000_000, currentPrice: 300, ipoPrice: 300, capitalRaised: 23_000_000, history: [288, 294, 300] }, 25_000_000);
assert.equal(legacyListing.valuationAtIPO, 100_000_000, 'IPO: legacy valuation was not normalized to 4x net worth');
assert(legacyListing.currentPrice < 100, 'IPO: legacy share price was not normalized with valuation');
assert(legacyListing.capitalRaised <= 12_500_000, 'IPO: legacy proceeds exceeded 0.5x net worth');
assert.equal(STARTING_CASH, 1_000, 'economy: new founder starting cash drifted');
assert.equal(RETAIL_ENTRY_COST, 500, 'economy: Retail entry cost drifted');
assert.equal(IPO_MIN_NET_WORTH, 10_000_000, 'IPO: late-game net-worth gate drifted');
assert.equal(IPO_MAX_NET_WORTH_PROCEEDS_MULTIPLE, 0.5, 'IPO: proceeds shortcut cap drifted');
assert.equal(CASINO_UNLOCK_NET_WORTH, 100_000, 'casino: late-game unlock drifted');
assert.equal(TAP_VALUE_CAP, 10, 'tap: hard per-tap value cap drifted');
assert.doesNotMatch(app, /tapRewardMultiplier|TAP_SOFT_START_TAPS|TAP_REWARD_FLOOR/, 'tap: App still applies tap-count diminishing returns');
assert.doesNotMatch(homeScreen, /tapRewardMultiplier|% REWARD|after momentum|reward never reaches zero/, 'tap: Home still displays tap-count reduction language');
assert.match(homeScreen, /no daily value reduction/, 'tap: unlimited-value explanation missing');
assert(PASSIVE_INCOME_CAP <= 4, 'economy: passive-income ceiling is too high');
assert(passiveIncomeMultiplier(1_000_000) > passiveIncomeMultiplier(25_000), 'passive income: wealth scaling is not increasing');
assert.match(app, /requestPurchase/, 'purchase: request missing');
assert.match(app, /Purchase was not confirmed/, 'purchase: confirmation guard missing');
assert.match(app, /Purchase not completed/, 'purchase: failure path missing');
assert.match(app, /finishTransaction/, 'purchase: transaction finishing missing');
assert.ok(app.includes('SafeAreaView edges={["top", "bottom", "left", "right"]}'), 'safe area: root edges missing');
assert.ok(businessScreen.includes("SafeAreaView edges={['left', 'right']}"), 'safe area: business nested edges missing');
assert.match(app, /setInterval\(saveNow, 5000\)/, 'timers: save interval missing');
assert.match(app, /return \(\) => clearInterval\(timer\)/, 'timers: App cleanup missing');
assert.match(businessScreen, /return \(\) => clearInterval\(timer\)/, 'timers: business cleanup missing');
assert.match(registration, /clearTimeout\(incorporationTimer\.current\)/, 'timers: registration cleanup missing');
assert.match(network, /clearInterval\(timer\)/, 'timers: clock observer cleanup missing');
const marketAsset = { id: 'market-test', symbol: 'MKT', name: 'Market Test', kind: 'STOCK' as const, price: 100, change: 0, dividend: 4, volatility: .02, history: [98, 100], sector: 'MOBILITY' as const };
assert.equal(applyMarketEvent([marketAsset], MARKET_EVENTS.find(event => event.id === 'ev-credit')!)[0].price, 108, 'market: EV shock failed');
assert.equal(calculateQuarterlyDividends([marketAsset], { 'market-test': { shares: 10 } }), 10, 'market: quarterly dividend failed');
assert.match(app, /watchlist/, 'market: watchlist is not persisted');
const limitOrder: LimitOrder = { id: 'limit-test', assetId: 'market-test', side: 'BUY', quantity: 2, limitPrice: 101, createdAt: 1, status: 'OPEN' };
const matchedLimit = matchLimitOrders([marketAsset], [limitOrder], 2);
assert.equal(matchedLimit.fills.length, 1, 'market: buy limit did not fill at or below target');
assert.equal(appendPortfolioPoint([], 2, 120).length, 1, 'market: portfolio history point missing');
assert.match(app, /onCreateLimitOrder/, 'market: limit-order callback missing');
assert.match(app, /portfolioHistory/, 'market: portfolio history persistence missing');
assert.match(read('src/screens/MarketScreen.tsx'), /LOCAL AI RIVALS/, 'market: local rival leaderboard missing');
assert.match(read('src/engine/marketEngine.ts'), /createSeededHistory/, 'market: seeded random-walk history missing');
assert.match(read('src/engine/marketEngine.ts'), /normalizeAssetHistories/, 'market: per-asset history normalization missing');
assert.match(app, /toFixed\(8\)/, 'market: fractional crypto precision missing');
assert.match(app, /Math.min\(100, cash \/ Math.max/, 'market: small-balance crypto buy path missing');
assert.match(read('src/screens/MarketScreen.tsx'), /Fractional units supported/, 'market: fractional crypto UI copy missing');
assert.match(app, /Gridline Power/, 'market: stock and business names are not separated');
assert.match(app, /67500/, 'market: crypto scale is not sensible');
assert.match(read('src/engine/marketEngine.ts'), /asset\.kind === 'CRYPTO' \? 0\.01/, 'market: sub-dollar crypto floor is not supported');
assert.match(lifestyleScreen, /imageBrand/, 'lifestyle: branded asset treatment is missing');
assert.match(read('src/screens/MarketScreen.tsx'), /playerNetWorth/, 'market: YOU row is not using player net worth');
assert.match(app, /showTestRewardedAd/, 'monetization: rewarded test placement missing');
assert.match(app, /soundEnabled/, 'settings: sound toggle is not wired');
assert.match(casinoScreen, /Math\.min\(50000, Math\.max\(100, Math\.floor\(netWorth \* 0\.01\)\)\)/, 'casino: net-worth-scaled session wager cap missing');
assert.match(read('src/services/notifications.ts'), /scheduleNotificationAsync/, 'notifications: scheduled reminder missing');
assert.match(homeScreen, /tapUpgradeLevel/, 'progression: tap value and upgrade level are not separate');
assert.match(homeScreen, /onWatchBoost/, 'monetization: Home rewarded placement missing');
assert.match(app, /CONFIRM REBIRTH/, 'progression: rebirth confirmation missing');
assert.match(ipoModal, /CONFIRM PUBLIC OFFERING/, 'IPO: confirmation dialog missing');
assert.match(read('src/components/modals/IPOAnnouncementModal.tsx'), /PUBLIC COMPANY FOUNDER/, 'IPO: milestone celebration missing');
assert.match(app, /first-ipo/, 'IPO: milestone achievement was not persisted');
assert.match(app, /Starter Stock Credit/, 'monetization: direct cash IAP shortcut was not removed');
assert.doesNotMatch(app, /Billionaire Club/, 'monetization: billionaire cash shortcut remains');
assert.match(businessHub, /lockedReason/, 'business UI: locked-action explanation missing');
assert.match(app, /ownedSectors/, 'events: owned-sector scoping missing');
assert(tapUpgradeGain(17, 5) > 0.5, 'tap ROI: level 17 gain is still flat at $0.50');
assert(tapUpgradeCost(17) > tapUpgradeCost(16), 'tap ROI: upgrade cost curve is not increasing');
assert(tapUpgradeCost(17) >= 5000 && tapUpgradeCost(17) <= 6200, 'tap ROI: level 17 cost left the corrected ~$5.8K range');
assert.match(read('scripts/ipo-economy-round7.ts'), /maxStepMultiple/, 'IPO: smooth-curve simulation missing');
assert.match(read('scripts/ipo-valuation-round9.ts'), /valuationToNetWorth/, 'IPO: structural valuation proof missing');
assert.match(app, /const safeListing = capIPOProceeds\(ipoListing, netWorth\)/, 'IPO: hydrated legacy listing normalization missing');
assert.match(homeScreen, /tapUpgradeGain/, 'tap UI: next-level ROI is not visible');
assert.match(read('src/config/buildInfo.ts'), /BUILD_VERSION/, 'settings: build version missing');
assert.match(read('src/config/buildInfo.ts'), /BUILD_COMMIT/, 'settings: build commit missing');
assert.match(app, /BrightGrid Energy/, 'migration: legacy BrightGrid asset name is not normalized');
assert.match(read('src/engine/businessSimulation.ts'), /normalizeBusinessNames/, 'migration: legacy business name is not normalized');
assert.match(read('src/engine/businessSimulation.ts'), /Sunward Gridworks/, 'business: distinct energy company name missing');
assert.match(businessScreen, /minHeight: 164/, 'business UI: header hero gap remains oversized');
assert.match(read('src/screens/BusinessScreen.tsx'), /flexShrink: 0/, 'business UI: active badge still lacks edge protection');
assert.match(read('src/screens/business/BusinessMasterHubScreen.tsx'), /IPO LOCKED/, 'IPO UI: pre-net-worth lock copy missing');
assert.match(homeScreen, /REBIRTH LOCKED/, 'rebirth UI: pre-net-worth lock copy missing');
assert.match(lifestyleScreen, /<LifestyleVisual item/, 'lifestyle UI: visuals are not item-specific');
assert.match(lifestyleScreen, /Image source=\{item\.image\}/, 'lifestyle UI: bundled image rendering missing');
assert.doesNotMatch(lifestyleScreen, /react-native-svg/, 'lifestyle UI: generic SVG asset visual remains');
const lifestyleCatalog = read('src/data/lifestyleCatalog.ts');
assert.doesNotMatch(lifestyleCatalog, /unsplash\.com/, 'lifestyle assets: remote image dependency remains');
assert.equal((lifestyleCatalog.match(/category: 'PRIVATE AVIATION'/g) || []).length, 2, 'lifestyle assets: aviation range missing');
assert.equal((lifestyleCatalog.match(/category: 'YACHTS & MARINE'/g) || []).length, 2, 'lifestyle assets: yacht range missing');
assert.match(read('src/screens/business/BusinessMasterHubScreen.tsx'), /scrollTo\(\{ y: 260/, 'retail: next-goal stock-order autofocus missing');
assert.match(read('src/screens/business/BusinessMasterHubScreen.tsx'), /saleFlash/, 'retail: sale feedback animation missing');
assert.match(homeScreen, /Share\.share/, 'virality: organic milestone share action missing');
assert.match(read('.github/workflows/emulator-screenshots.yml'), /emulator-screenshots/, 'build: emulator screenshot artifact missing');
assert.match(read('src/engine/businessSimulation.ts'), /salesRemainder/, 'retail: fractional sales accumulator missing');
assert.match(read('src/engine/businessSimulation.ts'), /demandEvent/, 'retail: timed demand pulse state missing');
assert.match(read('src/engine/businessSimulation.ts'), /const unitsDeducted =/, 'retail: unit deduction guard missing');
assert.match(read('src/engine/businessSimulation.ts'), /shelves empty; sales paused without operating-cost bleed/, 'retail: empty-shelf operating bleed guard missing');
assert.match(app, /businessAssetValue/, 'net worth: acquired business book value missing');
assert.match(businessHub, /PULSE CHAIN/, 'retail: customer pulse UI missing');
assert.match(app, /incomeEvents/, 'income ledger: source event state missing');
assert.doesNotMatch(read('src/engine/incomeLedger.ts'), /Tap actions/, 'income ledger: tap activity must not be an income source');
const incomeLedger = read('src/engine/incomeLedger.ts');
assert.doesNotMatch(incomeLedger, /tapHourly|tapIncomePerHour|tapRewardMultiplier|clickValue|tapsToday|tapBoostMultiplier|\* 600/, 'income ledger: tap must not be converted to an hourly rate');
assert.match(read('src/engine/incomeLedger.ts'), /Stocks · realized dividends/, 'income ledger: realized stock dividend source missing');
assert.match(homeScreen, /business &amp; investment sources/, 'income ledger: Home source label missing');
assert.match(read('src/components/modals/EarningsBreakdownModal.tsx'), /GAMEPLAY ACTIVITY/, 'income ledger: separate tap activity section missing');
assert.doesNotMatch(read('src/components/modals/EarningsBreakdownModal.tsx'), /Tap actions.*INCOME SOURCES/, 'income ledger: tap activity must not appear in source section');
assert.match(read('src/components/modals/EarningsBreakdownModal.tsx'), /INCOME SOURCES/, 'income ledger: breakdown modal missing');
assert.match(read('src/engine/businessSimulation.ts'), /hourlyByBusiness/, 'income ledger: per-business attribution missing');
assert.match(app, /buildIncomeSources\(\{ businesses, assets, holdings, businessProfitPerHour: profit \}\)/, 'income ledger: projected cashflow must use only business/investment inputs');
assert.match(read('scripts/tap-income-isolation-round14.ts'), /zeroTapVsThousandTap/, 'income ledger: tap-isolation proof missing');
assert.match(read('scripts/real-ledger-proof-round15.ts'), /1328\.92/, 'income ledger: real Copper & Bloom plus Ammu cab proof missing');
assert.match(read('scripts/economy-pacing-round8.ts'), /const tapCash = tapGain\(tapValue, profile, hour\);/, 'tap: pacing simulator still reduces value by tap count');
assert.match(read('src/screens/MarketScreen.tsx'), /FOUNDER COMMAND DECK/, 'visual system: market command-deck header missing');
assert.match(businessScreen, /#07130F/, 'visual system: business command-deck palette missing');
assert.match(read('src/screens/BusinessScreen.tsx'), /CommandDeckPulse/, 'visual system: Business shared pulse missing');
assert.match(read('src/screens/MarketScreen.tsx'), /CommandDeckPulse/, 'visual system: Markets shared pulse missing');
assert.match(read('src/screens/index.ts'), /HomeScreen/,'architecture: screen barrel missing');
assert.match(read('src/engine/index.ts'), /businessSimulation/,'architecture: engine barrel missing');
assert.match(read('src/types/marketAsset.ts'), /export interface Holding/,'architecture: shared market type missing');
assert.match(read('src/engine/tapBoostEngine.ts'), /TAP_BOOST_DURATION_MINUTES = 12/,'tap boost: 12-minute duration missing');
assert.match(read('src/screens/HomeScreen.tsx'), /TAP OVERDRIVE/,'tap boost: Home action missing');
assert.match(read('scripts/retail-mobility-hour-round11.ts'), /Retail \+ Mobility only/,'simulation: two-business proof missing');
console.log('Round 2 baseline regression matrix passed');
