declare const require: any;
const assert = require('assert').strict;
const fs = require('fs');
const path = require('path');
import { calculateOfflineReward, calculateOfflineSeconds, MAX_OFFLINE_SECONDS } from '../src/engine/offlineEarnings';
import { advanceGameTime, createInitialGameTime } from '../src/engine/gameTimeEngine';
import { DEFAULT_BUSINESSES, simulateBusinessTick } from '../src/engine/businessSimulation';
import { DEFAULT_PROGRESSION, hydrateDailyProgress } from '../src/types/progression';
import { businessValuation, createIPOListing, getIPOEligibility } from '../src/engine/ipoEngine';
import { MARKET_EVENTS, applyMarketEvent, appendPortfolioPoint, calculateQuarterlyDividends, matchLimitOrders } from '../src/engine/marketEngine';
import { LimitOrder } from '../src/types/market';
import { tapUpgradeCost, tapUpgradeGain } from '../src/engine/tapUpgradeEngine';

const root = process.cwd();
const read = (file: string) => fs.readFileSync(path.join(root, file), 'utf8');
const app = read('App.tsx');
const gameContext = read('src/context/GameContext.tsx');
const businessScreen = read('src/screens/BusinessScreen.tsx');
const homeScreen = read('src/screens/HomeScreen.tsx');
const registration = read('src/components/modals/BusinessRegistrationModal.tsx');
const network = read('src/context/NetworkContext.tsx');
const businessHub = read('src/screens/business/BusinessMasterHubScreen.tsx');
const ipoModal = read('src/components/modals/IPOLaunchModal.tsx');

assert.match(app, /AsyncStorage\.getItem\(SAVE\)/, 'save/load: AsyncStorage load path missing');
assert.match(app, /JSON\.parse\(raw\)/, 'save/load: JSON parse path missing');
assert.match(app, /latestState\.current/, 'save/load: latest state snapshot missing');
assert.match(gameContext, /hydrated/, 'save/load: business hydration gate missing');
assert.equal(calculateOfflineSeconds(1000 + MAX_OFFLINE_SECONDS * 1000 * 4, 1000), MAX_OFFLINE_SECONDS, 'offline earnings: 24-hour cap failed');
assert.equal(calculateOfflineSeconds(1000, 1000 + 2 * 60 * 60 * 1000), 0, 'offline earnings: rollback failed');
assert.equal(calculateOfflineReward(3600001, 1, 3600), 3600, 'offline earnings: hourly payout failed');
assert.equal(calculateOfflineReward(3600001, 1, 3600, true), 0, 'offline earnings: tamper guard failed');
const clock = createInitialGameTime(10_000);
assert.equal(advanceGameTime(clock, 11_000).gameTimestamp - clock.gameTimestamp, 300_000, 'clock: five simulated minutes per real second failed');
const retail = { id: 'regression-retail', name: 'Regression Retail', sector: 'Retail' as const, isUnlocked: true, unlockNetWorthRequired: 0, isAcquired: true, acquisitionCost: 2500, legalStatus: 'Licensed_Legal' as const, policeHeat: 0, stability: 92, hourlyNetProfit: 0, stockUnits: 10, maxStockCapacity: 2500, pricingTier: 'Standard' as const, hasSecurity: false, hasManager: false, unitWholesaleCost: 2, monthlyRent: 800, monthlyPayroll: 1200 };
const retailTick = simulateBusinessTick([retail], 2);
assert.equal((retailTick.businesses[0] as typeof retail).stockUnits, 5, 'retail: stock deduction failed');
assert.equal(retailTick.cashDelta, 16.15, 'retail: sale revenue/tax settlement failed');
assert.equal(simulateBusinessTick([{ ...retail, stockUnits: 0 }], 2).cashDelta, 0, 'retail: empty inventory payout failed');
assert.equal(DEFAULT_BUSINESSES.length, 10, 'businesses: ten-sector catalog missing');
const expansion = DEFAULT_BUSINESSES.find(item => item.sector === 'Energy')!;
assert.equal(simulateBusinessTick([{ ...expansion, isAcquired: true }], 2).businesses[0].isAcquired, true, 'businesses: expansion sector tick failed');
assert.match(businessScreen, /Math\.max\(0, value \+ result\.cashDelta\)/, 'wallet: passive payout clamp missing');
assert.match(app, /Math\.max\(0, n - total\)/, 'wallet: trade spend clamp missing');
const firstLogin = hydrateDailyProgress(DEFAULT_PROGRESSION, Date.UTC(2026, 0, 1));
const nextLogin = hydrateDailyProgress(firstLogin, Date.UTC(2026, 0, 2));
const missedLogin = hydrateDailyProgress(nextLogin, Date.UTC(2026, 0, 4));
assert.equal(firstLogin.loginStreak, 1, 'progression: first streak failed');
assert.equal(nextLogin.loginStreak, 2, 'progression: consecutive streak failed');
assert.equal(missedLogin.loginStreak, 1, 'progression: missed streak reset failed');
assert.match(app, /missionClaimed/, 'progression: mission state missing');
assert.ok(DEFAULT_PROGRESSION.achievements.length === 0 && DEFAULT_PROGRESSION.prestigeLevel === 0, 'progression: late-game defaults missing');
assert.match(homeScreen, /REBIRTH EMPIRE/, 'progression: prestige control missing');
assert.match(homeScreen, /WEEKLY EVENT/, 'progression: weekly event UI missing');
assert.match(homeScreen, /onOpenNextGoal/, 'goal: next-goal card is not tappable');
assert.match(app, /focusRetail/, 'goal: Retail stock-order route is not wired');
const ipoBusiness = { ...retail, hourlyNetProfit: 2000 };
assert.equal(getIPOEligibility({ ...ipoBusiness, isAcquired: false }, null).eligible, false, 'IPO: unacquired company was eligible');
assert.equal(getIPOEligibility(ipoBusiness, null).eligible, true, 'IPO: eligible company was blocked');
const listing = createIPOListing(ipoBusiness, Date.UTC(2026, 0, 1));
assert.equal(getIPOEligibility(ipoBusiness, listing).eligible, false, 'IPO: duplicate public offering was allowed');
assert.match(app, /requestPurchase/, 'purchase: request missing');
assert.match(app, /Purchase was not confirmed/, 'purchase: confirmation guard missing');
assert.match(app, /Purchase not completed/, 'purchase: failure path missing');
assert.match(app, /finishTransaction/, 'purchase: transaction finishing missing');
assert.ok(app.includes('SafeAreaView edges={["top", "bottom", "left", "right"]}'), 'safe area: root edges missing');
assert.ok(businessScreen.includes("SafeAreaView edges={['left', 'right']}"), 'safe area: business nested edges missing');
assert.match(app, /setInterval\(saveNow, 5000\)/, 'timers: save interval missing');
assert.match(app, /return \(\) => clearInterval\(timer\)/, 'timers: App cleanup missing');
assert.match(businessScreen, /return \(\) => clearInterval\(timer\)/, 'timers: business cleanup missing');
assert.match(registration, /clearTimeout\(incorporationTimer\.current\)/, 'timers: registration cleanup missing');
assert.match(network, /clearInterval\(timer\)/, 'timers: clock observer cleanup missing');
const marketAsset = { id: 'market-test', symbol: 'MKT', name: 'Market Test', kind: 'STOCK' as const, price: 100, change: 0, dividend: 4, volatility: .02, history: [98, 100], sector: 'MOBILITY' as const };
assert.equal(applyMarketEvent([marketAsset], MARKET_EVENTS.find(event => event.id === 'ev-credit')!)[0].price, 108, 'market: EV shock failed');
assert.equal(calculateQuarterlyDividends([marketAsset], { 'market-test': { shares: 10 } }), 10, 'market: quarterly dividend failed');
assert.match(app, /watchlist/, 'market: watchlist is not persisted');
const limitOrder: LimitOrder = { id: 'limit-test', assetId: 'market-test', side: 'BUY', quantity: 2, limitPrice: 101, createdAt: 1, status: 'OPEN' };
const matchedLimit = matchLimitOrders([marketAsset], [limitOrder], 2);
assert.equal(matchedLimit.fills.length, 1, 'market: buy limit did not fill at or below target');
assert.equal(appendPortfolioPoint([], 2, 120).length, 1, 'market: portfolio history point missing');
assert.match(app, /onCreateLimitOrder/, 'market: limit-order callback missing');
assert.match(app, /portfolioHistory/, 'market: portfolio history persistence missing');
assert.match(read('src/screens/MarketScreen.tsx'), /AI RIVAL INVESTORS/, 'market: rival leaderboard missing');
assert.match(read('src/engine/marketEngine.ts'), /createSeededHistory/, 'market: seeded random-walk history missing');
assert.match(read('src/engine/marketEngine.ts'), /normalizeAssetHistories/, 'market: per-asset history normalization missing');
assert.match(app, /toFixed\(8\)/, 'market: fractional crypto precision missing');
assert.match(app, /Math.min\(100, cash \/ Math.max/, 'market: small-balance crypto buy path missing');
assert.match(read('src/screens/MarketScreen.tsx'), /Fractional units supported/, 'market: fractional crypto UI copy missing');
assert.match(app, /Gridline Power/, 'market: stock and business names are not separated');
assert.match(app, /67500/, 'market: crypto scale is not sensible');
assert.match(read('src/engine/marketEngine.ts'), /asset\.kind === 'CRYPTO' \? 0\.01/, 'market: sub-dollar crypto floor is not supported');
assert.match(app, /icon === 'car'/, 'lifestyle: car visual is missing');
assert.match(app, /icon === 'jet'/, 'lifestyle: jet visual is missing');
assert.match(read('src/screens/MarketScreen.tsx'), /playerNetWorth/, 'market: YOU row is not using player net worth');
assert.match(app, /showTestRewardedAd/, 'monetization: rewarded test placement missing');
assert.match(app, /soundEnabled/, 'settings: sound toggle is not wired');
assert.match(app, /maxExposure = 50000/, 'casino: session wager cap missing');
assert.match(read('src/services/notifications.ts'), /scheduleNotificationAsync/, 'notifications: scheduled reminder missing');
assert.match(homeScreen, /tapUpgradeLevel/, 'progression: tap value and upgrade level are not separate');
assert.match(homeScreen, /onWatchBoost/, 'monetization: Home rewarded placement missing');
assert.match(app, /CONFIRM REBIRTH/, 'progression: rebirth confirmation missing');
assert.match(ipoModal, /CONFIRM PUBLIC OFFERING/, 'IPO: confirmation dialog missing');
assert.match(businessHub, /lockedReason/, 'business UI: locked-action explanation missing');
assert.match(app, /ownedSectors/, 'events: owned-sector scoping missing');
assert(tapUpgradeGain(17, 5) > 0.5, 'tap ROI: level 17 gain is still flat at $0.50');
assert(tapUpgradeCost(17) > tapUpgradeCost(16), 'tap ROI: upgrade cost curve is not increasing');
assert(tapUpgradeCost(17) >= 48000 && tapUpgradeCost(17) <= 50000, 'tap ROI: level 17 cost left the expected ~$49K range');
assert.match(homeScreen, /tapUpgradeGain/, 'tap UI: next-level ROI is not visible');
assert.match(read('src/config/buildInfo.ts'), /BUILD_VERSION/, 'settings: build version missing');
assert.match(read('src/config/buildInfo.ts'), /BUILD_COMMIT/, 'settings: build commit missing');
assert.match(app, /BrightGrid Energy/, 'migration: legacy BrightGrid asset name is not normalized');
assert.match(read('src/engine/businessSimulation.ts'), /normalizeBusinessNames/, 'migration: legacy business name is not normalized');
assert.match(read('src/engine/businessSimulation.ts'), /Sunward Gridworks/, 'business: distinct energy company name missing');
assert.match(businessScreen, /minHeight: 164/, 'business UI: header hero gap remains oversized');
assert.match(read('src/screens/BusinessScreen.tsx'), /flexShrink: 0/, 'business UI: active badge still lacks edge protection');
assert.match(read('src/screens/business/BusinessMasterHubScreen.tsx'), /IPO LOCKED/, 'IPO UI: pre-net-worth lock copy missing');
assert.match(homeScreen, /REBIRTH LOCKED/, 'rebirth UI: pre-net-worth lock copy missing');
assert.match(app, /<LifestyleVisual item=\{x\}/, 'lifestyle UI: visuals are not item-specific');
assert.match(read('src/screens/business/BusinessMasterHubScreen.tsx'), /scrollTo\(\{ y: 260/, 'retail: next-goal stock-order autofocus missing');
assert.match(read('src/screens/business/BusinessMasterHubScreen.tsx'), /saleFlash/, 'retail: sale feedback animation missing');
assert.match(homeScreen, /Share\.share/, 'virality: organic milestone share action missing');
assert.match(read('.github/workflows/build-android.yml'), /emulator-screenshots/, 'build: emulator screenshot artifact missing');
assert.match(read('src/engine/businessSimulation.ts'), /salesRemainder/, 'retail: fractional sales accumulator missing');
assert.match(read('src/engine/businessSimulation.ts'), /demandEvent/, 'retail: timed demand pulse state missing');
assert.match(read('src/engine/businessSimulation.ts'), /unitsDeducted > 0 \? Number/, 'retail: empty-shelf operating bleed guard missing');
assert.match(app, /businessAssetValue/, 'net worth: acquired business book value missing');
assert.match(businessHub, /PULSE CHAIN/, 'retail: customer pulse UI missing');
console.log('Round 2 baseline regression matrix passed');
