import { DEFAULT_BUSINESSES, simulateBusinessOperations } from '../src/engine/businessSimulation';
import { BusinessEntity } from '../src/types/business';

const HOUR_SECONDS = 3600;
function makeOwnedPair(): BusinessEntity[] { return DEFAULT_BUSINESSES.filter(item => item.id === 'apex-retail' || item.id === 'metro-mobility').map(item => item.id === 'apex-retail' ? { ...item, isAcquired: true, stockUnits: 2500, autoRestockEnabled: false, operatingRampSeconds: 0 } : { ...item, isAcquired: true, operatingRampSeconds: 0 }); }
function beforeModel() { const retailUnitsPerHour = 2 * 1800; const retailRevenue = retailUnitsPerHour * 5.5; const retailLegacyNet = retailRevenue - 66.67; const mobilityLegacyNet = 10 * 2200; const synergy = 1.04; return { retailEntry: 5000, starterStock: 500, retailRevenue, retailCogs: 0, retailTax: 0, retailFixedCosts: 66.67, mobilityOperatingCosts: 0, hourlyCashflow: Number(((retailLegacyNet + mobilityLegacyNet) * synergy).toFixed(2)), explanation: 'Legacy comparison: full-speed production, no operating ramp, and Retail COGS/tax omitted.' }; }
function afterModel() {
  let businesses = makeOwnedPair(); let events = 0; let lastHourlyByBusiness: Record<string, number> = {};
  for (let minute = 0; minute < 60; minute += 1) { const result = simulateBusinessOperations(businesses, 60, 60, 100_000, {}, 0); businesses = result.businesses; lastHourlyByBusiness = result.hourlyByBusiness; events += result.events.length; }
  const retail = businesses.find(item => item.id === 'apex-retail')!; const mobility = businesses.find(item => item.id === 'metro-mobility')!;
  const retailCashflow = retail.pendingSettlementAmount || 0; const mobilityCashflow = mobility.pendingSettlementAmount || 0; const combined = Number((retailCashflow + mobilityCashflow).toFixed(2));
  return { retailEntry: 500, starterStock: 500, retailCashflowFirstHour: Number(retailCashflow.toFixed(2)), mobilityCashflowFirstHour: Number(mobilityCashflow.toFixed(2)), combinedCashflowFirstHour: combined, currentSteadyHourlyCashflow: combined, retailHourlyNetAfterRamp: retail.hourlyNetProfit, mobilityHourlyNetAfterRamp: mobility.hourlyNetProfit, retailCogsAndTaxIncluded: true, retailFixedCostsPerMonth: 2000, retailAutoRestockCost: 250, operatingRampHours: 4, settlementInterval: '1 hour', events, minimumCash: 100_000, explanation: 'Operations update every 2 seconds; cash is credited once after the hour settles.' };
}
const before = beforeModel(); const after = afterModel(); const output = { scope: 'Retail + Mobility only · one hour', before, after, delta: { firstHourCashflowReduction: Number((before.hourlyCashflow - after.combinedCashflowFirstHour).toFixed(2)), steadyStateDifference: Number((before.hourlyCashflow - after.currentSteadyHourlyCashflow).toFixed(2)) }, rootCause: ['The old path credited hourly revenue every 2 seconds, effectively paying 1,800 times per hour.', 'Mobility started with 10 sedans at $2,200/hour each, so it contributed $22,000/hour before synergy.', 'The old Retail path omitted inventory COGS and legal tax from the cashflow comparison.'], fixes: ['Operations still update every 2 seconds, but the wallet receives only whole-hour settlement credits.', 'New businesses ramp over four real-time hours.', 'Retail subtracts $2/unit COGS, 15% legal tax, and prorated rent/payroll.', 'Empty Retail shelves produce $0 and do not bleed rent/payroll.'] };
if (after.minimumCash < 100_000) throw new Error('Two-business simulation cash floor failed'); if (after.combinedCashflowFirstHour >= before.hourlyCashflow) throw new Error('Before/after cost curve did not reduce first-hour spike'); console.log(JSON.stringify({ ...output, result: 'PASS' }, null, 2));
