// @ts-nocheck
const assert = require('node:assert/strict');
const fs = require('node:fs');
require.extensions['.webp'] = (module, filename) => { module.exports = filename; };
const { createSeededHistory } = require('../src/engine/marketEngine');
const { calculateIndex, STOCK_INDEX_DEFINITIONS, CRYPTO_INDEX_DEFINITIONS } = require('../src/engine/indexEngine');
const { processQuarterlyDividends } = require('../src/engine/dividendEngine');
const { scheduledEventForTick, applyScheduledEvent } = require('../src/engine/marketEventEngine');
const { migrateGameSave, GAME_SAVE_VERSION } = require('../src/engine/saveMigration');
const { STOCK_CATALOG } = require('../src/data/stocksData');
const { CRYPTO_CATALOG, cryptoCatalogAsset } = require('../src/data/cryptoData');
const moduleSource = fs.readFileSync('src/screens/markets/MarketsModuleScreen.tsx', 'utf8');
const appSource = fs.readFileSync('App.tsx', 'utf8');

const stocks = STOCK_CATALOG.map(item => ({ ...item, kind: 'STOCK', change: 0, dividend: item.dividendYield, history: createSeededHistory(item.id, item.price, item.volatility) }));
const crypto = CRYPTO_CATALOG.map(cryptoCatalogAsset);
const stockHolding = { shares: 10, avgPrice: stocks[0].price, realized: 0, realizedPnl: 0 };
const cryptoHolding = { shares: 2.5, avgPrice: crypto[0].price, realized: 0, realizedPnl: 0 };
const stockDividend = processQuarterlyDividends(stocks, { [stocks[0].id]: stockHolding }, '2025-Q4', Date.UTC(2026, 0, 5));
assert(stockDividend.payout > 0);
assert.equal(processQuarterlyDividends(stocks, { [stocks[0].id]: stockHolding }, '2026-Q1', Date.UTC(2026, 1, 5)).payout, 0);
const stockIndex = calculateIndex(stocks, STOCK_INDEX_DEFINITIONS[0]);
const techIndex = calculateIndex(stocks, STOCK_INDEX_DEFINITIONS[2]);
const cryptoIndex = calculateIndex(crypto, CRYPTO_INDEX_DEFINITIONS[0]);
assert(stockIndex.constituents.length === stocks.length);
assert(techIndex.constituents.length > 0);
assert(cryptoIndex.constituents.length === crypto.length);
const event = scheduledEventForTick(12);
assert(event && event.kind === 'STOCK');
const changed = applyScheduledEvent(stocks, event);
assert.notEqual(changed[0].price, stocks[0].price);
const migrated = migrateGameSave(JSON.stringify({ schemaVersion: 10, cash: 100, assets: stocks, holdings: {}, tradeHistory: [], watchlist: [] }));
assert.equal(GAME_SAVE_VERSION, 11);
assert.equal(migrated.lastDividendQuarter, '');
assert.deepEqual(migrated.marketEventHistory, []);
assert.match(moduleSource, /channelHoldings/);
assert.match(moduleSource, /channelSummary/);
assert.match(moduleSource, /calculateIndex/);
assert.match(moduleSource, /No positions/);
assert.match(moduleSource, /paddingBottom:92/);
assert.match(appSource, /processQuarterlyDividends/);
assert.match(appSource, /marketEventHistory/);
assert.doesNotMatch(moduleSource, /paddingBottom:150/);
console.log(JSON.stringify({ ok: true, saveSchema: GAME_SAVE_VERSION, catalogs: { stocks: stocks.length, crypto: crypto.length }, portfolioIsolation: { stocks: stockHolding.shares, crypto: cryptoHolding.shares }, indices: { globalConstituents: stockIndex.constituents.length, techConstituents: techIndex.constituents.length, cryptoConstituents: cryptoIndex.constituents.length }, scheduledEvent: { id: event.id, headline: event.headline, shock: event.shock }, firstQuarterDividend: stockDividend.payout, layoutGuards: ['no outer Markets ScrollView', 'channel-specific holdings/summary/allocation', 'compact chart/list padding', 'readable muted text'] }, null, 2));
