declare const require: any;
const assert = require('assert').strict;
import { technicalSnapshot, evaluateAlerts } from '../src/engine/marketIntelligenceEngine';
import { migrateGameSave, GAME_SAVE_VERSION } from '../src/engine/saveMigration';
import { Asset } from '../src/types/marketAsset';
import { PriceAlert } from '../src/types/marketIntelligence';

const history = Array.from({ length: 60 }, (_, index) => 100 + index * 0.8 + Math.sin(index / 3) * 2);
const snapshot = technicalSnapshot(history);
assert(snapshot.sma20 !== null && snapshot.ema12 !== null && snapshot.ema26 !== null, 'moving averages missing');
assert(snapshot.rsi14 !== null && snapshot.macd !== null && snapshot.signal9 !== null, 'momentum indicators missing');
assert(snapshot.bollingerUpper !== null && snapshot.bollingerLower !== null, 'Bollinger bands missing');
assert.equal(snapshot.trend, 'UPTREND', 'trend should follow EMA12 > EMA26');
const asset: Asset = { id: 'proof', symbol: 'PRF', name: 'Proof Systems', kind: 'STOCK', price: 112, change: 1, dividend: 0, volatility: .02, history };
const alerts: PriceAlert[] = [{ id: 'a1', assetId: asset.id, symbol: asset.symbol, name: asset.name, condition: 'ABOVE', target: 110, baselinePrice: 100, enabled: true, createdAt: 1 }];
const evaluated = evaluateAlerts(alerts, [asset], 2);
assert.equal(evaluated.triggered.length, 1, 'above-price alert did not trigger');
assert.equal(evaluated.alerts[0].enabled, false, 'triggered alert was not disabled');
assert.equal(evaluated.alerts[0].triggeredAt, 2, 'trigger timestamp missing');
const migrated = migrateGameSave({ schemaVersion: 9, priceAlerts: [{ ...alerts[0], target: 'bad' }, alerts[0]] });
assert.equal(GAME_SAVE_VERSION, 10, 'Round 23 schema version missing');
assert.equal(migrated.priceAlerts.length, 1, 'invalid alert was not sanitized');
console.log(JSON.stringify({ indicators: { sma20: snapshot.sma20, ema12: snapshot.ema12, ema26: snapshot.ema26, rsi14: snapshot.rsi14, macd: snapshot.macd, signal9: snapshot.signal9, bollingerUpper: snapshot.bollingerUpper, bollingerLower: snapshot.bollingerLower, trend: snapshot.trend }, alert: { triggered: evaluated.triggered[0].reason, disabled: !evaluated.alerts[0].enabled }, migration: { version: GAME_SAVE_VERSION, validAlerts: migrated.priceAlerts.length } }, null, 2));
