// @ts-nocheck
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const bank = require('../src/engine/bankEngine');
const types = require('../src/types/bank');
const { migrateGameSave } = require('../src/engine/saveMigration');
const now = Date.UTC(2026, 0, 1);
const state = types.defaultBankState(now);
const score = bank.creditBreakdown({ ...state, ficoScore: 740, savingsBalance: 30_000 });
assert.equal(score.tier, 'Good');
assert.equal(score.pointsToVeryGood > 0, true);
const deposit = bank.openDeposit('CD_3M', 1000, now);
assert.equal(deposit.maturesAt, now + 3 * 24 * 60 * 60 * 1000);
const tax = bank.calculateTax(120_000, 10_000, 5_000, 50_000);
assert.equal(tax.federal > 0, true);
assert.equal(tax.payroll > 0, true);
assert.equal(bank.insuranceSpec('CYBER').coverage, 60_000);
const event = bank.bankEventForTick(1, now);
assert.equal(['RATE_HIKE', 'RECESSION', 'FUNDING_BOOM'].includes(event.kind), true);
const ledgerState = bank.addLedger({ ...state, deposits: [deposit] }, 'DEPOSIT', 'Test CD', 1000, now, 'proof');
assert.equal(ledgerState.ledger.length, 1);
const achievementState = { ...ledgerState, ficoScore: 800, loans: [bank.createLoan(ledgerState, 'SBA_MICROLOAN', 1000, 10, now)] };
assert( bank.achievementIds(achievementState, 1_000_000).includes('FIRST_LOAN') );
const migrated = migrateGameSave({ schemaVersion: 12, cash: 1000 });
assert.equal(migrated.schemaVersion, 13);
assert.equal(migrated.bankState.schemaVersion, 2);
const sourceFiles = ['src/data/stocksData.ts', 'src/data/cryptoData.ts', 'src/screens/LifestyleScreen.tsx', 'src/screens/BusinessScreen.tsx'];
sourceFiles.forEach(file => assert.equal(fs.existsSync(path.join(root, file)), true));
console.log(JSON.stringify({ passed: true, credit: { tier: score.tier, pointsToVeryGood: score.pointsToVeryGood }, deposit: { name: deposit.name, termDays: deposit.termDays, maturityDeltaDays: 3 }, tax: { federal: tax.federal, state: tax.state, payroll: tax.payroll, capitalGains: tax.capitalGains }, insurance: bank.insuranceSpec('CYBER'), marketEvent: event.kind, ledgerEntries: ledgerState.ledger.length, migration: { schemaVersion: migrated.schemaVersion, bankSchema: migrated.bankState.schemaVersion }, untouchedModules: 'verified-present' }, null, 2));
